### ISSUE TITLE
Errors with age-retention

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#100]
In make_fish_selex, the indexing for retain_a was erroneously referring to fleet fs, not f.
Fixed the above and sent to Max.

Still need to fix the creation of average retain_a for use in benchmark and forecast.
Also, age-retention is not being output in report.sso.

**Comment by Rick-Methot-NOAA** [comment]
@k-doering-NOAA .  Github thinks this branch is ahead by 2 commits, and the comments suggest that a bit more work should be done.  What else do you remember about this branch?

**Comment by Rick-Methot-NOAA** [comment]
I checked the network graph, which is very nice!, and see that this was never merged back into main.  I will do a compare and get this taken care of next.

**Comment by k-doering-NOAA** [comment]
sounds good, good idea to look at the network graph! I don't have anything to add. In case this is helpful (although this may have been what you meant by compare): https://github.com/nmfs-stock-synthesis/stock-synthesis/compare/main...issue%23100_age-retention

**Comment by Rick-Methot-NOAA** [comment]
manually (using ultracompare) transfer the changes made in age-retention branch into the main branch.
This includes:  

- correct reference to fleet index (f vs fs) in selex
- creating average age-retention (discard_a) in setup for benchmark
- reporting of Aret (e.g. discard_a) in Age_Selex section of report.sso

the age_retention branch will be removed.

**Comment by Rick-Methot-NOAA** [comment]
The manual update had failed to create the average retain_a and discmort_a used by benchmark.  Add this code today to main branch.  Testing done using Irish cod example provided by M. Cardinale
