### ISSUE TITLE
New M equation for SS

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#102]
Email from Mark Maunder (part of larger conversation with Rick with the same subject line as this issue):
> I had a go at implementing the age and sex structured M in the SS function.
> I still need some quantities such as the Mat_slope_Fem and Mat50%_FemXX as well as the maturity at age vector.
> I have not tested the code since it requires all the SS code to work.
> Let me know what the next step would be."

Attached file includes Mark's changes (renamed to .txt because github doesn't support .tpl attachments): 
[natmort.tpl.txt](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/5563481/natmort.tpl.txt)

**Comment by Rick-Methot-NOAA** [comment]
Just realized another fringe case to deal with.  If growth or maturity is time-varying and Maunder's M links to maturity, then the time-varying flag for M needs to be turned on.  The way to do this is when the timevary flags are created. 
I will deal with this after the merge as a tune-up to the new M code

**Comment by k-doering-NOAA** [comment]
> Just realized another fringe case to deal with. If growth or maturity is time-varying and Maunder's M links to maturity, then the time-varying flag for M needs to be turned on. The way to do this is when the timevary flags are created.
> I will deal with this after the merge as a tune-up to the new M code

@Rick-Methot-NOAA , good catch. could an error msg with informative msg be provided for the fringe case in the meantime? Hopefully this could be quickly added until there is time available to work on the fringe case.

**Comment by Rick-Methot-NOAA** [comment]
Not yet.  We really need to lean on Mark and his team to document and
test.  This is a Beta feature at best right now.
