### ISSUE TITLE
review SPR/YPR profile

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#112]
A user noted that SPR/YPR profile was incomplete for a particular model and noted that it was not produced if the Hessian was NPD.
 
It is not produced for NPD Hessian because it is only produced after the Hessian step.  This is because it forces changes to selectivity so could interfere with gradients.  But global MSY calculations make similar changes and it is allowed to happen before the Hessian.  This situation needs review.  

Also should review the code used to calculate the biology and selectivity for the profile. It should be same as the logic used to create biology and selectivity for the benchmark

**Comment by Rick-Methot-NOAA** [comment]
I think this may be a relic issue that needs no action, but please check r4ss

**Comment by k-doering-NOAA** [comment]
Yes, this is no longer a problem, due to a change in ADMB (see https://github.com/admb-project/admb/issues/164).
