### ISSUE TITLE
switch to compiling with ADMB 12.3 upon its release

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#123]
ADMB 12.3 will likely be released soon (probably in the next few weeks). Should we test it out once available and try to switch over to compiling SS with this version? I think there would be several advantages, including a fix that should speed up runs (relative to ADMB 12.2), the -hess_step option, and a fix for reading input files with OSX9 line endings.

**Comment by k-doering-NOAA** [comment]
ADMB 12.3 has been released: https://github.com/admb-project/admb/releases/tag/ADMB-12.3 so we can start transitioning.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , would you mind asking IT to get admb 12.3 onto tumnus and mac mini? not too much a rush, given we have gh actions, but we may still need it sometimes.

I've update all the builds on gh actions (currently in a [branch](https://github.com/nmfs-stock-synthesis/stock-synthesis/tree/test_admb_12_3)) and am now testing that admb 12.3 works as expect on jenkins. We should know tomorrow if it does, and can merge in the branch at that time.

**Comment by iantaylor-NOAA** [comment]
Request submitted for Tumnus (linux server at NWFSC).
Installing on the mac mini shared by a few of us at NWFSC created some errors noted at https://github.com/admb-project/admb/issues/197.

**Comment by iantaylor-NOAA** [comment]
ADMB 12.3 has now been successfully installed on both Tumnus and the Mac mini.

**Comment by kellijohnson-NOAA** [comment]
For what it is worth, i was able to successfully compile SS with the new version.

**Comment by k-doering-NOAA** [comment]
Thanks so much @iantaylor-NOAA, I appreciate the help! And thanks Kelli, that is good to know; it also compiled on my machine.

@Rick-Methot-NOAA , have you been able to upgrade? I think we can close this issue once you have upgraded and pull request #144 is merged in, then just used 12.3 to compile from now on.

**Comment by Rick-Methot-NOAA** [comment]
I have switched.  So we are good to go
