### ISSUE TITLE
setup job on github actions to compile ss with warnings

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#131]
@nschindler-noaa included a warnings options in the [ss build script for unix](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/Make_SS_330_new.sh). It would be great to create a job on github actions that runs the command so we can see the current warnings. If it makes sense to, we could also make the job fail if there are any warnings coming from ss, although I'm not sure this is a good idea or not.

**Comment by k-doering-NOAA** [comment]
Got this working in a new job called build-warnings : https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/gh_actions_warn/.github/workflows/build-warnings.yml, left the final version in a branch for now. I did need to modify build with warning script slightly, but I think since it will mainly be used only on gh actions from now on it should be fine.

It looks like there are 2 warnings that are coming directly from the ss source code:
https://github.com/nmfs-stock-synthesis/stock-synthesis/runs/2179920503?check_suite_focus=true#step:6:36

I'm not sure these warnings require changes in the code or if they are warnings that can be safely ignored.

I'm thinking to make this job more useful, perhaps I could find a way to pipe the warnings to a text file, filter out only the onces that pertain to SS, and then cause the job to fail if any new warnings appear? I could see running this script either every commit on main or pull request to main only or perhaps on a schedule (e.g., run weekly on main).

@Rick-Methot-NOAA , any thoughts on what would be useful info to you as the primary developer?

**Comment by Rick-Methot-NOAA** [comment]
It is good to see these warnings.  Both could be ignored.  I added one line to the code so the 2nd will not occur.  The first is a relic, but is a read item, so a pain to remove.

**Comment by k-doering-NOAA** [comment]
Thanks @Rick-Methot-NOAA ! I will ignore the first warning, then, but then have the job fail if any additional new warnings pop up so we don't miss them. We shall see how that goes...

**Comment by k-doering-NOAA** [comment]
Ok, I switched the OS from Centos to Ubuntu to simplify this run, but now there are some different warnings popping up. These are the  types that I think are related to SS:
1. ss.cpp: In function ‘void create_timevary(dvector&, ivector&, ivector&, int&, const int&, const ivector&, const int&, const dvector&, int&, const double&)’:
ss.cpp:191:69: warning: unused parameter ‘parm_adjust_method’ [-Wunused-parameter]
  191 |                        const ivector &block_design_pass, const int &parm_adjust_method,
      |                                                          ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
2. ss.cpp: In member function ‘void model_parameters::get_natmort()’:
ss.cpp:12408:23: warning: implicitly-declared ‘dvariable& dvariable::operator=(const dvariable&)’ is deprecated [-Wdeprecated-copy]
12408 |                 natM1=natM2;
      |                       ^~~~~
3.  ss.cpp: In member function ‘void model_parameters::get_selectivity()’:
ss.cpp:13456:28: warning: this statement may fall through [-Wimplicit-fallthrough=]
13456 |             scaling_offset = 2;
      |             ~~~~~~~~~~~~~~~^~~
4. ss.cpp: In member function ‘void model_parameters::write_nudata()’:
ss.cpp:23432:60: warning: ‘newobs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
23432 |      if(Svy_minval(f)>=0.0 && Svy_errtype(f)!=0) newobs=max(newobs,0.5*Svy_minval(f));
      |                                                         ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~

@Rick-Methot-NOAA , sorry to ask this again, but which (if any) do you think are imporant to show for SS? I now have code to remove warnings that aren't relavant, so we can remove or retain as needed.

**Comment by Rick-Methot-NOAA** [comment]
Unless the list is a lot longer than this, let's keep them all so we are
constantly reminded.

Of these, I have looked at the unused parm_adjust_method and it is a benign
issue.

**Comment by k-doering-NOAA** [comment]
These are the four types, although in total, it is 80 warnings, most of them like 2. 

Ok, perhaps I will "keep" them and investigate more what the other ones are. I suspect 2. might actually be an admb issue that isn't that important, but I'm not totally sure. 

I think I will set this job up so it "fails" if any additional errors (or types of errors) show up. Maybe we will see how that goes  and adjust as needed.

**Comment by Rick-Methot-NOAA** [comment]
OK.  I will work on type #2.

working on SPR reporting now.

*Richard D. Methot Jr. Ph.D.**NOAA Fisheries Senior Scientist** for Stock
Assessments*

*Mobile: 301-787-0241*
