### ISSUE TITLE
interpretation of "final" parameter in sex-specific selectivity offset with double normal

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#134]
The Spiny Dogfish and Dover Sole assessments being conducted right now at NWFSC are both showing evidence of sex-specific selectivity (likely due to differences in distribution of the sexes for both species). Vlada and Chantel, leading these assessments, are exploring the use of the parameter offset option available for double-normal selectivity (set using a value of 3 or 4 in the "Male" column of the selex pattern input). This worked well for Big Skate in 2019 where the estimated selectivity was asymptotic. However, @chantelwetzel-noaa discovered some unusual patterns emerging when the "Scale" parameter is below the transformed "Final".

I replicated Chantel's patterns using the BigSkate_2019 model in the ss-examples repository (see figure below). The "final" = 0 for the main selectivity (males), which corresponds to selectivity = 0.5 and the "final" offset parameter is fixed at 0. The "scale" parameter is fixed at either 0.7 (left) or 0.3 (right).

It might be better to have the final value be scaled relative to the peak for each sex, rather than on the same 0 to 1 range. That would allow the scale parameter to scale down all elements of the curve equally without having to estimate an offset from final to achieve a similar shape, rather than allowing in somewhat strange patterns like the one on the right. If backwards compatibility is important, this could be new options 5 and 6, although the change would just be in interpretation of the offset, where any dome-shaped pattern should still be achievable through a slightly different parameter value.

Even if no change or addition is made to SS, it could be useful to expand the Selex24 spreadsheet to include the offset parameters.

![image](https://user-images.githubusercontent.com/4992918/108259970-97818880-7116-11eb-856d-5fc9015a57a4.png)

**Comment by Rick-Methot-NOAA** [comment]
starting work on this now.  I suspect that I will create a new selectivity option rather than make a current one even more complicated with options

**Comment by Rick-Methot-NOAA** [comment]
The combinations get complex very quickly.  I cannot imagine how to modify this approach without creating new, hard to test, situations with equally weird patterns.
I will start by copying current selex 24 and copying into currently discontinued selex 2, so we can use selex 2 as a testbed.
I really want to streamline the code for this selex 2.  There are TOO MANY "if" statements!  But the testing of any modification would be a big undertaking.

**Comment by iantaylor-NOAA** [comment]
I'm sure there's a lot of complexity that I don't understand, but this is the sequence that I imagined:

1. calculate a new set of 6 derived double-normal parameters values using 6 base parameters & 4 sex offsets
2. use those 6 derived values to calculate a double normal curve with max = 1.0 for the offset sex
3. use the 5th sex offset parameter (SzSel_*_Scale) to rescale the curve calculated in step 2

**Comment by Rick-Methot-NOAA** [comment]
I can try that.  Although it does not seem logical to scale the smallest fish.  Making the degree of scaling conditional on length maturity curve seems ideal, but another order of operations quagmire.

**Comment by iantaylor-NOAA** [comment]
I hadn't thought about how the current approach applies the same Size_DblN_start value for both sexes. Adding an offset for that parameter could allow it to counteract any rescaling. Or maybe this is a reason why the dogleg option is the better choice for cases where scale is the primary difference between sexes as it allows the selectivity to start equal and diverge at larger sizes.

**Comment by Rick-Methot-NOAA** [comment]
Got it.  This simple code change applies the scale to the final as well as the peak:
//              point2=1.0/(1.0+mfexp(-final));
              point2=Apical_Selex/(1.0+mfexp(-final));

I am implementing this as selex pattern 2 (which was a previously deprecated option).
Kathryn - no need for a Jenkins on this as no existing model uses selex pattern 2.
I will push to the repo
Rick
