### ISSUE TITLE
expand capability of hermaphroditism function

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#139]
from Skyler Sagarese and SEFSC colleagues
for the scamp assessment
(1) Hermaphroditism function: currently the probability of transition for age 0 is 0 and is determined for the remaining ages based on the input parameters for the cumulative normal distribution. For scamp, the probability of transition should equal 0 for age 1, but we are not able to implement that in SS currently (small non-zero value is predicted for age 1). Could this change be incorporated into SS, either by adding an input age at which the herm function is used and below which the probability of transition = 0 or by entering a vector for the probability of transition, similar to the input for age-based maturity or fecundity?

  (2) male + female SSB: We have had lots of discussions during this assessment (as well as previous assessments) regarding the units of spawning stock biomass. Some suggestions have been to weight the relative contribution of male SSB to female SSB (e.g., 0.5 male SSB for every 1 female SSB) rather than assume 1 kg of female SSB is equivalent to 1 kg of male SSB. We can code this up from the report file, but it might be helpful if this feature could be built into SS. I imagine this modification would become extremely important and useful for hermaphroditic species, including our ongoing gag grouper assessment.
@skylersagarese-NOAA

**Comment by Rick-Methot-NOAA** [comment]
got a first cut done.
new input format looks like:
1 #_hermaphroditism option:  0=none; 1=female-to-male age-specific fxn; -1=male-to-female age-specific fxn
-1.2 # Hermaphro_season.first_age 
0.5 # fraction_of_maleSSB_added_to_total_SSB 
pushing code to the branch

**Comment by Rick-Methot-NOAA** [comment]
Kathryn,
please add documentation in the manual.
I will pull code into main

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA I opened an issue. Is this still the correct inputs to access the option?

> new input format looks like:
> 1 #_hermaphroditism option: 0=none; 1=female-to-male age-specific fxn; -1=male-to-female age-specific fxn
> -1.2 # Hermaphro_season.first_age
> 0.5 # fraction_of_maleSSB_added_to_total_SSB

**Comment by Rick-Methot-NOAA** [comment]
correct.  Please add this to the manual

**Comment by skylersagarese-NOAA** [comment]
Here are some notes that I added when I set up my file
-1.2 # Hermaphro_season.first_age (-1 means all seasons); fractional part will be converted to the first age that switches sex
1 # fraction_of_maleSSB_added_to_total_SSB (fraction ranging from 0.0 to 1.0 of the male SSB added into the total SSB)

**Comment by k-doering-NOAA** [comment]
Thanks @skylersagarese-NOAA ! Closing this, since it is merged into main and we have another issue open for the manual.
