### ISSUE TITLE
likelihood values for some quantities with lambda = 0 not getting reported

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#140]
Vlada Gertseva and I noticed inconsistent reporting of the likelihoods for values with lambda = 0.

The mean size at age likelihood is only calculated when the lambda > 0 controlled by this line:
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/e28f64dc3a4eb00f842fcdddd03d3b61ccfa1d18/SS_objfunc.tpl#L458

In contrast, other components also do the calculation if save_for_report > 0, as below:
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/e28f64dc3a4eb00f842fcdddd03d3b61ccfa1d18/SS_objfunc.tpl#L157

I can push this change if you want, but don't want to get in the way of ongoing work in other branches. I also haven't done a comprehensive search of which other likelihood components are missing the `|| save_for_report>0`.

**Comment by Rick-Methot-NOAA** [comment]
Go for it.  I am far away from that part of the code.
get the issue included in the new project tab

**Comment by iantaylor-NOAA** [comment]
Issue resolved in Pull Request #141. 
I've changed the Issue Prioritization to "Done" and will close this issue. 
It is listed on the [3.30.17 release issues](https://github.com/nmfs-stock-synthesis/stock-synthesis/milestone/1) Milestone so can be noted on the change log if appropriate.
