### ISSUE TITLE
add more version tags to repository

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#145]
The SS source code is currently not tagged between v 3.30.02 and 3.30.10. Create tags based on versions that were [announced](https://vlab.ncep.noaa.gov/web/stock-synthesis/public-forums/-/message_boards/category/988476) and are archived on the google drive.

**Comment by Rick-Methot-NOAA** [comment]
do you have the older change log (excel version) in which much of the info is recorded?

**Comment by iantaylor-NOAA** [comment]
Sorry to add more things to the mix, but the history of the `SS_versioninfo_330safe.tpl` file seems to show exactly which commits had a version number changed going back to 3.30.0.0 in 2016: https://github.com/nmfs-stock-synthesis/stock-synthesis/commits/main/SS_versioninfo_330safe.tpl

It's possible that sometimes the version number got incremented but then a subsequent bug fix was made before the executable got uploaded. However, if the goal here is really just to provide a way to get Mac or Linux executables which match the Windows exes that were in use at the time, then there's always the option to compare the results across operating systems to confirm that match.

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA that is a really smart way to look over version history (and yes, good foresight, haha). There are definitely some commits in the logs that say things like "add change to previous commit", but we don't exactly know which was the last commit when the exes were compiled anyway, except by version number.

**Comment by k-doering-NOAA** [comment]
Now added. Hopefully this will help browsing older history of the code, for example with the [compare tool](https://github.com/nmfs-stock-synthesis/stock-synthesis/compare/).
