### ISSUE TITLE
parameter bound check improvement

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#147]
A "nan" for SoftBoundPen was tracked to this situation:

parm initial value was < parm min
AND
-stopph = 0.

so this code in Check_Parm function did not set parm initial value to parm min:
    else if(Pval<Pmin && PrPH>=0)
    {N_warn++;
    	 warning<<N_warn<<" "<<" parameter init value is less than parameter min "<<Pval<<" < "<<Pmin<<" for parm: "<<iparm<<endl;
    	echoinput<<" parameter init value is less than parameter min "<<Pval<<" < "<<Pmin<<" for parm: "<<iparm<<endl; NewVal=Pmin;}
    else if(Pval>Pmax && PrPH>=0)
    {N_warn++; 
    	 warning<<N_warn<<" "<<" parameter init value is greater than parameter max "<<Pval<<" > "<<Pmax<<" for parm: "<<iparm<<endl;
    	echoinput<<" parameter init value is greater than parameter max "<<Pval<<" > "<<Pmax<<" for parm: "<<iparm<<endl; NewVal=Pmax;}

Recommendation:
remove the PrPH>=0 condition for those checks so that Pmin <= Pval <=Pmax is always enforced.
@iantaylor-NOAA  What do you think?

**Comment by iantaylor-NOAA** [comment]
I can't imagine a situation where you would want a parameter fixed outside the bounds.
However, if the parameters are fixed, I could imagine problems associated with automatically changing the initial value to go within the bounds. Maybe it would be better to just exit put it on the user to fix their bounds or initial values. I think that would be reasonable whether the parameter was fixed or estimated.

**Comment by k-doering-NOAA** [comment]
Here is the warning I see in Darkblotched_2015: 

```
parameter init value is greater than parameter max 99 > 2 for parm: 7
```
Is there any way to get a more informative name for the parameter? I think that would be helpful for users trying to hunt down which parameter is causing the issue. Otherwise, I think the warning has a good level of info!

**Comment by Rick-Methot-NOAA** [comment]
I echoed the same warning to echoinput, so I was hoping where it appears in echoinput would be enough of an indicator of where the problem is.
I will check on possibility of passing the cumulative parameter ID to this function call.  If that is easy, then I can easily put parameter name in the warning message.

**Comment by k-doering-NOAA** [comment]
the echoinput output makes it really easy to find which parameter has the error. So maybe just make the warning.sso more generic and refer folks to echoinput.sso?
"Parameter init value is greater than parameter max. See end of echoinput.sso for more details."

Some other observations from our test set:
1. Now fixed values need to be within bounds, too, which was not previously the case. All the values flagged in our models were fixed values outside the min/max bounds. I suspect many people who had models that would run before now will need to update their bounds. Does it seem ok to require this?
2.  -999 is a code commonly used for some doublenormal selectivity parameters that are fixed. Now, this must also be in the parameter bounds.

**Comment by Rick-Methot-NOAA** [comment]
I will make these changes and will create an exception for Pval <-900

Cannot make exception for all fixed values because SS cannot always tell
difference between a permanently fixed value and a value temporarily fixed
because maxphase=0.

Rick

**Comment by Rick-Methot-NOAA** [comment]
revised such that new warning and action is:
see echoinput for parm_type, will exit if prior requested

**Comment by k-doering-NOAA** [comment]
New warning looks good!
what does "will exit if prior requested" mean?

**Comment by Rick-Methot-NOAA** [comment]
The problem with bad parameter bounds mostly occurs when the prior
probability depends upon the Pval being between Pmin and Pmax.

So now the code examines the bounds and displays bad conditions in the
warning, but if that parameter does not have a prior to be calculated, then
it plays through after displaying the warning.  It only exits if a prior is
requested, thus avoiding a crash of some sort later.

**Comment by k-doering-NOAA** [comment]
I see, thanks for the explanation! I am in the process of updating the test models and fully testing this change.

What about a slight wording change: "SS will stop early if prior requested for this parameter" ?

**Comment by k-doering-NOAA** [comment]
I think this works as expected, based on the jenkins testing. Jenkins tests now all passing again, too.

I still think the slight wording change above would be helpful, though, but otherwise, I think testing for this issue is complete.
