### ISSUE TITLE
phase out translation exe after 3.30.17 release

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#151]
The ss_trans.exe version has been a valuable tool for Stock Synthesis users updating their models from 3.24 to 3.30. However, many models have now been converted and there is a fair amount of maintenance involved in keeeping this version up to date as new features are added to SS.

Phase out the transition executable after the 3.30.17 to reduce the burden of maintenance. User could still use up to SS 3.30.17 to update their 3.24 model to 3.30, and then could do an additional run to update to the latest version of SS once there are versions later than 3.30.17.

- [x] Stop building trans version of the exe after 3.30.17 release on github actions.
- [ ] Add warning to build scripts that trans exe can no longer be built
- [x] Remove translation specific code from the SS codebase 

Assigning myself for now, but may ping others for help. This issue is "on hold" until after the 3.30.17 release.

**Comment by k-doering-NOAA** [comment]
Will need to edit the documentation in the manual on how to transition from 3.24 to 3.30 after phasing out the translation exe.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA, I added you as an assignee. I wasn't sure if there was additional code besides the read*3.24.tpl files, so just wanted to check if there was other code to delete?

**Comment by Rick-Methot-NOAA** [comment]
The only other code is the make file, but there seems little overhead associated with keeping these files in the repo.  So let us not delete for now.  Just stop testing them with each update of 3.30.

**Comment by k-doering-NOAA** [comment]
I think we should delete them, as they will still remain in git. We can easily get back to the 3.30.17 tag to see the files. While I agree there is little overhead, if we aren't using the files, they cause some clutter, making it harder to find the essential code.

**Comment by Rick-Methot-NOAA** [comment]
OK.  We also have them in the google folder

**Comment by k-doering-NOAA** [comment]
Closing (after labeling resolved and with the 3.30.18 milestone), as this is finished. Ended up just removing the portions or entire build scripts with trans, as a warning felt unnecessary (given very few people compile the trans exe)
