### ISSUE TITLE
time-vary growth discrepancy

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#155]
In the 1st year with time-vary growth parameters, the design is that those new growth parameters will affect in-season growth for that year and growth to the start of the next year.

However, examination of model output indicates that for the first age after Amin, the size at that age is affected already at the beginning of the year with the time-vary parameters.

In a limited test, if Amin = 1 (or presumably 1 .0 or higher), the calculations work correctly.
But if Amin = 0.0 or 0.01, the first age after Amin is getting updated with the current year's growth parameters.

**Comment by Rick-Methot-NOAA** [comment]
Initial finding is that the lack of synchrony in updating growth at the correct time step was introduced when density-dependent parameter option was worked on.  At that time, it was found necessary to create wt_at_age before the time-vary parameter call was made.  This used the length-at-age which already had been projected to the beginning of the relevant year using the previous year's growth parameters.  Then to calculate wt_at_age, it was necessary to call Make_AgeLength_Key.  ALK relies on a flag (nseas*Nsubseas) to know which ALKs need updating that year.
The problem was that this new call to Make_AgeLength_Key turned off that flag.  So, later in that year loop after the growth parameters may have been updated, the flag was off.
The flag works like below
   ALK_idx=(s-1)*N_subseas+subseas;
   if(ALK_subseas_update(ALK_idx)==1) //  so need to calculate
   {
   ALK_subseas_update(ALK_idx)=0;  //  reset to 0 to indicate update has been done

So, since for density-dependence we only need season 1 subseas 1 updating, add this in top of the year loop in function: get_time_series in SS_popdyn.tpl

          ALK_subseas_update(1)=1;  // do 1st subseas of 1st season;  ADD THIS LINE for 3.30.17

All other subseasons are within the year, so do not get ALK calculation until after growth is updated with any time-varying growth parameters.

Still hunting down a fringe issue before I submit this for full testing.

Rick

**Comment by Rick-Methot-NOAA** [comment]
This is now resolved, after two days of sleuthing.  A modification of simple's control.ss with time blocks for growth was create to aid in the testing.  Several anomalies were found in the order in which ss_popdyn was calling get_growth2() and get_growth3().  Most of the problem was due to lack of calls to growth3 following up on growth2 and prior to calling Make_AgeLength_KeyKey().  This then interacted with how the linear portion of growth below Amin was updated.  I will commit this testing branch soon.  Need to remove a bunch of extra outputs first.

**Comment by k-doering-NOAA** [comment]
I tested with a time varying growth model and  I see no difference at all between MEAN_BODY_WT(Begin) report:48 and MEAN_SIZE_TIMESERIES report:49 between 3.30.16 and the issue#154_smrybio branch or between the current main branch and issue#154_smrybio branch. Perhaps this is good, but it is confusing why this time varying growth discrepancy is not showing up? Unless the issue was observed as a result of work on a different branch, perhaps https://github.com/nmfs-stock-synthesis/stock-synthesis/tree/natmort-maturity?

**Comment by Rick-Methot-NOAA** [comment]
I observed the issue while working on the fix for the smrybio branch.  Perhaps the problem was created and subsequently solved all while working within the smrybio branch.
My suggestion for a code review of growth module stands as it still seems to me that some configurations may still create anomalies especially as time-vary growth transitions from the young fish linear growth phase to the growth curve.
