### ISSUE TITLE
SPR/YPR report not written to report file even if hessian is inverted

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#158]
I noticed that in several models (running from current  main branch), The `
 SPR/YPR_Profile report:54`  item in the control file is not written, but instead the statement `This output only included after the Hessian is inverted`  is shown, despite the fact the hessian was estimated for these models. I think this statement may not be working properly (perhaps wrote_bigreport not getting updated to be greater than 0?):
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/a923c2546dd9bff6aafd43c63bf2528a05d2f32e/SS_write_report.tpl#L3250-L3254

**Comment by Rick-Methot-NOAA** [comment]
The logic hoop jumps I went through to get things not to report twice is the source of this problem.  I'll take a look.

**Comment by Rick-Methot-NOAA** [comment]
A flag, SDmode, is created in readstarter and is 1 if Hessian is to be attempted, or 0 if -nohess is used.
This flag is now used to improve the logic of which reports to do at the end of the the run after sdreport is completed.

NOTE for future code improvement:
Global MSY and SPR/YPR profile currently are in write_report, but with some complicated logic
They could be moved into functions similar to write_Bzero_output and called from FINAL section in global.
