### ISSUE TITLE
Implement bounded env_link for density-dependent parameters

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#165]
Thanks to @nathanvaughan-NOAA for discovering this. The bounded init link is [not implemented](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/bd721572cb2ad8d452756145db4794400757788f/SS_timevaryparm.tpl#L347) for linking a parameter to a model-derived quantities. I just tried running a model with this option - simple but with [this selectivity line](https://github.com/nmfs-stock-synthesis/ss-test-models/blob/56a86200529ca9e8537387194e52af8d250ee0a6/models/Simple/control.ss#L240) changed to 

```
19            70        36.653            30          0.01             1          2          -303        0          0          0          0          0          0  #  Size_inflection_SURVEY1(2)
```

and got the error `array bound exceeded -- index too high in prevariable::operator()`

I think it would be helpful to either implement the bounded init link (could code just be copy/pasted from the [env links section](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_timevaryparm.tpl#L202-L214)?) or to provide a more informative error msg on why this option is not available or allowed. We may need want to update the manual, too based on what is implemented.

**Comment by Rick-Methot-NOAA** [comment]
I took a look and it is not as easy as it would seem.
Time-vary links to env input data are all processed before the popdyn timeseries.
but density_dependence must be processed on a year-to-year basis.  But the needed parm_min and parm_max values are not available to easily be passed.
The information created in the switch() on line 24 of SS_timevaryparm.tpl needs to be made available to the FUNCTION for processing density_dependence.

That info looks like it could all be processed in prelim_calcs and stored for use later by both the regular and the d-d timevary functions.

**Comment by Rick-Methot-NOAA** [comment]
These are constants, so can be processed when timevary parms are created:
          baseparm_min=MGparm_LO(timevary_setup(2));
          baseparm_max=MGparm_HI(timevary_setup(2));

then they can be stored as additional elements in the array:  timevary_def[tvary](1,14);

this is done in the function create_timevary() in SS_global.tpl.
so would add baseparm min and max to the list below:
//  where timevary_byyear is a selected column of a year x type matrix (e.g. timevary_MG) in read_control
//  timevary_setup(1)=baseparm type;
//  timevary_setup(2)=baseparm index;
//  timevary_setup(3)=first timevary parm
//  timevary_setup(4)=block or trend type
//  timevary_setup(5)=block pattern
//  timevary_setup(6)=env link type
//  timevary_setup(7)=env variable
//  timevary_setup(8)=dev vector used
//  timevary_setup(9)=dev link type
//  timevary_setup(10)=dev min year
//  timevary_setup(11)=dev maxyear
//  timevary_setup(12)=dev phase
//  timevary_setup(13)=all parm index of baseparm
//  timevary_setup(14)=continue_last dev

**Comment by k-doering-NOAA** [comment]
Ah, I see; it seems reasonable to just add a clear error message for now that this feature is not implemented.

**Comment by Rick-Methot-NOAA** [comment]
Note:   need check to be sure that Fcast_specifiy_selectivity flag is set to 1 (use annual parms) if density-dependence is used.
