### ISSUE TITLE
modify/remove warning for rec_dist option 4?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#167]
This warning is fairly common in a lot of models:
```
This model has just one settlement event; recommend changing to recr_dist_method 4 which takes no recr_dist parameters
```
I have heard a lot of users who are unclear if 1) this warning indicates a problem in their model (it doesn't) or 2) run into issues because the warning does not make it clear that the 3 parameter lines needed for recruitment option 2 aren't needed for option 4.

It would probably be helpful to either remove this warning altogether or adjust it. One example of how it could be modified: 
```
This model has just one settlement event; recommend changing to recr_dist_method 4 which takes no recr_dist parameters. Note that the parameter lines for recruitment distribution in MG parms are not needed and should be removed when switching to recr_dist_method 4.
```

**Comment by iantaylor-NOAA** [comment]
I like the use of this warning to nudge people toward simpler configurations that produce identical results. Without the warning very few people would make the change. But I agree that the longer warning would be better.

**Comment by k-doering-NOAA** [comment]
I think that is true, it is helpful to nudge folks toward the simpler configuration, but many people have asked me (when requesting help with an SS model) if this warning means the model is not set up correctly. I'm not sure how to communicate that it does not indicate a problem with the model within the warning message, but maybe giving the extra guidance on how to switch to recruitment distribution 4 is enough?

**Comment by iantaylor-NOAA** [comment]
How about making the warning something like `This model has just one settlement event. Changing to recr_dist_method 4 and removing the recruitment distribution parameters at the end of the MG parms section (below growth parameters) will produce identical results and simplify the model.`

**Comment by Rick-Methot-NOAA** [comment]
I like it

**Comment by k-doering-NOAA** [comment]
Yes, that is great!
