### ISSUE TITLE
run fast models on github actions instead of jenkins?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#170]
The run-no-est job is proving helpful, because it runs automatically through github actions and provides feedback on the job status (green checkmark if it passed, red x if it did not). We have been relying on jenkins to run the testing models with estimation. This is helpful because running the entire model set takes ~ 9 hrs, and there is a 6 hr limit on a github actions job. However, the disadvantage with Jenkins is we don't have a way to run it automatically and the status of the job is not visible on github.

Perhaps an improvement would be to run the fastest models with estimation on github actions. Approximately half of the model set takes less than 5 min to run, so perhaps it would be useful to start just with running this set? I think in total these model runs would take less than an hour, providing relatively quick feedback.

Longer term, we could spend time trying to figure out ways to speed up the longer running models - maybe there are small changes we could make to speed up the runs?

[Models](https://github.com/nmfs-stock-synthesis/ss-test-models/tree/main/models) that take less than 5 min to run:

growth_timevary/
Hake_2018/
Hake_2019_semi-parametric_selex/
Empirical_Wtatage_Age_Selex/
Simple_NoCPUE/
Simple/
Simple_with_Discard/
tagging_mirrored_sel/
three_area_nomove/
vermillion_snapper/
three_area/
growth_morphs/
KelpGreenling2015/
BigSkate_2019/

**Comment by Rick-Methot-NOAA** [comment]
I like your logic here and appreciate the list of model run times.  I support creating a github auto-run for these fast models
