### ISSUE TITLE
fix after merge with natmort_again

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#171]
One issue detected with growth_morphs is that only the main morph was getting fecundity-at-age assigned.  Should be easy fix.

Other issue is a subtle change in calculations leading  to SSB_unfished is causing a difference in variance of that quantity and consequently, variance in forecast quantities.

creating new branch:  fix_main

**Comment by Rick-Methot-NOAA** [comment]
Fix the growth_morph issue.
Problem was in the indexing.  Previously the wt_len fxn looped only Gpat, then Make_Fecundity looped g and found the associated Gpat.
With platoon usage, there are several platoons per Gpat.
So when get_mat_fec  was created from the previous arrangement of functions, it used the wt_len loop approach, which only processes the middle g for each Gpat.  So, several g's were getting no fecundity assigned.
Revise such that get_mat_fec() now loops all the g's and finds the associated Gpat=GP4(g).

**Comment by Rick-Methot-NOAA** [comment]
The above fix eliminates the difference for the growth_morph model.

For big_skate, the only thing unique about this model is that it uses growth option 8.
@k-doering-NOAA here is a suggested, long-shot approach to next line of investigation:
1  run .16 and get par file, -nohess
2.  run current code and get par fil , -nohess
3. verify that they are the same
4. set all the growth parameters to be fixed (not estimated).  
5. run both models and get variance
6. compare to see if the variance is the same when no growth parameters are estimated.

**Comment by Rick-Methot-NOAA** [comment]
for big_skate, I see some differences in the numbers_at_length table that I will investigate.  They are for the middle (M) of the first year (1916).  Suspect that the relevant ALK is not getting updated properly.  The total numbers across all sizes are correct, but they are in shifted bins for that one year.

**Comment by Rick-Methot-NOAA** [comment]
I found and fixed the indexing issue causing the numbers-at-length output problem.  Alas, it did not fix the main variance issue with big skate.  I will now switch it to a different growth curve to see if that resolves the variance issue.  What else could be unique about this model setup?????

**Comment by iantaylor-NOAA** [comment]
In case it helps, here's the Big Skate model with Von Bertalanffy growth:
[BigSkate2019_VBgrowth.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/6423787/BigSkate2019_VBgrowth.zip)

If a variance issue remains, I might try removing the mean length at age data, which has lambda = 0 so SHOULD have zero influence, but I remember Vlada saying that she thought there was some impact when a similar setup was used for dogfish leading her to remove the data entirely.

**Comment by k-doering-NOAA** [comment]
I see the Parm_softbounds likelihood component also changed very slightly, is there any way this could affect variance estimates?

The features mentioned on the model readme are `Uses F method 3 (hybrid), Cessation growth model, Catchability time blocks, catchability priors, discard data.`

I don't know if this is useful or not, but here are some recent changes to the main branch (since teh Merge pull request #162 from nmfs-stock-synthesis/fix-spr-report  commit) : https://github.com/nmfs-stock-synthesis/stock-synthesis/compare/f6eb3dc...main .

**Comment by k-doering-NOAA** [comment]
Also, there were small changes in the forecast catch se for growth_timevary and Hake_2019_semi-parametric_selex. Just so small that they were below the tolerance that we have set to flag the values as "changed" (and when rounding quantities to 3 digits, it is not apparent).


quantity | value | ref_value | diff | perc_change | ratio | mod_name
-- | -- | -- | -- | -- | -- | --
ForeCatch_2012_se | 8.98E+04 | 8.98E+04 | 3.00E-01 | 3.34E-04 | 1.000003 | growth_timevary
ForeCatch_2021_se | 3.55E+05 | 3.55E+05 | -1.00E+00 | -2.82E-04 | 0.999997 | Hake_2019_semi-parametric_selex

**Comment by Rick-Methot-NOAA** [comment]
Switching to different growth curve for big skate did not solve issue.
I just compared for simple.  Shows the same pattern:  small difference in se for SSB_unfished, which then causes small differences in variance for the forecast quantities.
I know where to look in the code now.

**Comment by Rick-Methot-NOAA** [comment]
Took ALL day, but I found the culprit on the variance issue.  Not exactly, but I narrowed it down to the replacement of make_fecundity with get_mat_fec in popdyn.

**Comment by e-perl-NOAA** [comment]
Resolved in PR #173
