### ISSUE TITLE
More control for recr_dist in forecast

### ISSUE THREAD

**Issue by akatan999** [nmfs-stock-synthesis/stock-synthesis#179]
In the newest (test) version of SS, it is possible to use the random walk (option 23) to model recruitment distribution in a multi-area model and at the same time control the value of the recruitment distribution that is assumed for the forecast period. However, this combination only work when using average recruitment in the forecast period but it does not work if using the SR to determine recruiment in the forecast period. It would be very useful for multi-area model to be able to use option 23 to model recruitment distribution but at the same time be able to use SR for recruitment in the forecast as it is the case for yellowfin tuna model in the Indian Ocean.
Cheers
Max

**Comment by Rick-Methot-NOAA** [comment]
Max:  having more control on recdist in area models would be beneficial for projections as with option 23 those will stay at the last estimated value (which for short term forecast (1-2y) is the most likely one) but at the same time still be able to use the SR

**Comment by Rick-Methot-NOAA** [comment]
The need is for:
So, a new Option 5 that would do recruitment from Spawn_recr and do averaging for recr_distribution.

**Comment by Rick-Methot-NOAA** [comment]
including a small fix to placement of save_parm = 0; so it applies more universally.

**Comment by Rick-Methot-NOAA** [comment]
Noting that the revisions here were not documented in text of forecast.ss_new:
`1 #_Forecast recruitment:  0= spawn_recr; 1=value*spawn_recr_fxn; 2=value*VirginRecr; 3=recent mean from yr range above (need to set phase to -1 in control to get constant recruitment in MCMC)
`
also, It was not described in the manual at:  6.4 Forecast Recruitment Adjustment

Work on this alongside #68

**Comment by Rick-Methot-NOAA** [comment]
Upon further consideration, it seems that some of the changes should have been to Fcast_rec_yr2, rather than to recdev_end. I will create a new branch to work on this.

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA can we close this issue?
