### ISSUE TITLE
consider new informative names for DM parameters

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#185]
See more comments in #183 . Here is one suggestion:

Couldn't you use a delimiter and just paste the fleets together if there are multiple? e.g., ln(DM_theta)_Age_P7(2-3-4)
For what it is worth, I like the correct mathematical notation of ln(DM_theta) because it helps the visually impaired when a screen reader is reading the output. I think there are ways in tidyverse to accommodate the parenthesis, at least you can with backticks but I think there are other ways as well.

_Originally posted by @kellijohnson-NOAA in https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/183#issuecomment-861718915_

**Comment by k-doering-NOAA** [comment]
relates to #266

**Comment by Rick-Methot-NOAA** [comment]
I started into implementing the more informative names with the code for MV Tweedie.  Some aspects of the proposed names get complicated.  I do not see an easy way to list in the name all the fleets that use that parameter.

**Comment by iantaylor-NOAA** [comment]
Could we just expand the Length_Comp_Fit_Summary and Age_Comp_Fit_Summary outputs to include columns for the parameter labels? 

Perhaps you've already implemented changes to this table for MV Tweedie, but it occurs to me that it could be expanded from this status-quo format:
Age_Comp_Fit_Summary |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Factor | Fleet | Recommend_var_adj | # | N | Npos | min_Nsamp | max_Nsamp | mean_Nsamp_in | mean_Nsamp_adj | mean_Nsamp_DM | DM_theta | mean_effN | HarMean_effN | Curr_Var_Adj | Fleet_name
5 | 1 | 1 | # | 47 | 47 | 13 | 1440 | 473.255 | 473.255 | 215.072 | 0.829148 | 1273.44 | 70.6253 | 1 | Fishery
5 | 2 | 1 | # | 14 | 14 | 46 | 105 | 69.5 | 69.5 | 64.3659 | 12.3422 | 284.77 | 32.8397 | 1 | Acoustic_Survey

to something like

Age_Comp_Fit_Summary |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Factor | Fleet | Recommend_var_adj | # | N | Npos | min_Nsamp | max_Nsamp | mean_Nsamp_in | mean_Nsamp_adj | mean_Nsamp_DM | weight_par1 | weight_par2 | weight_Label1 | weight_Label2 | mean_effN | HarMean_effN | Curr_Var_Adj | Fleet_name
5 | 1 | 1 | # | 47 | 47 | 13 | 1440 | 473.255 | 473.255 | 215.072 | 0.829148 | NA | ln(DM_theta)_1 | NA | 1273.44 | 70.6253 | 1 | Fishery
5 | 2 | 1 | # | 14 | 14 | 46 | 105 | 69.5 | 69.5 | 64.3659 | 12.3422 | NA | ln(DM_theta)_2 | NA | 284.77 | 32.8397 | 1 | Acoustic_Survey

where both `weight_Par` and `weight_Label` values would be NA for the multinomial likelihood, the 2nd one would be NA for the DM, and both would have meaning for the MV Tweedie.

That would make it easy to match each fleet with the parameter.

**Comment by Rick-Methot-NOAA** [comment]
Good suggestion Ian.

**Comment by Rick-Methot-NOAA** [comment]
Realizing that the addition of the 2 parameter Tweedie causes problems for the logic of the current indexing approach, which refers to parameter number.  Revise the indexing approach to refer to method no., and for each method create index to the parameters it uses.  This will be backward compatible as parameter and method are synonymous when only 1 parm per method.
