### ISSUE TITLE
Add output of F at Blimit

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#188]
Typically the fishery management plan sets Blimit = 0.5*Bmsy
There is desire to be able to report on the F associated with Blimit.
There already is information on this in the YPR/SPR profile, but so specific search for the F producing Blimit.
There already is a search capability for the F that produces a specific B/B0.  So, if user already knows the Blimit relative to B0, they could use that.
Another search could be added after the FMSY search to be the F_Blimit search

**Comment by Rick-Methot-NOAA** [comment]
first cut at code to do this:
a.  replicate the Btarget search code after the MSY search code
b.  in the replicated code, search for 50% of B_MSY rather than user input Btgt
c.  save that Fmult and use it in the SPR/YPR profile.

Next need to provide user control of what % of B_MSY to use.
@chantelwetzel-noaa please comment.

**Comment by Rick-Methot-NOAA** [comment]
Finished.
Input format looks like:
3 # Benchmarks: 0=skip; 1=calc F_spr,F_btgt,F_msy; 2=calc F_spr,F0.1,F_msy;  3=add F_Blimit
2 # MSY: 1= set to F(SPR); 2=calc F(MSY); 3=set to F(Btgt) or F0.1; 4=set to F(endyr) 
0.4 # SPR target (e.g. 0.40)
0.342 # Biomass target (e.g. 0.40)
-0.25 # COND: Do_Benchmark==3;  Blimit as fraction of Bmsy (neg value to use as frac of Bzero) (e.g. 0.50)

Output in Mgmt_Quant is also conditional and looks like:
B_MSY/SSB_unfished 0.296192 0
SSB_Blim 13102.8 0
annF_Blim 0.171883 0
Dead_Catch_Blim 3630.43 0
ForeCatch_2002 713.68 0

The Fmult associated with Blimit is also used in SPR/YPR profile and shows up as item 8 in that list.

**Comment by chantelwetzel-noaa** [comment]
This looks like a reasonable approach.  In the above example the F at the Bmsy fraction would reflect the F at 25% of unfished biomass. Is that correct?

**Comment by Rick-Methot-NOAA** [comment]
Correct.  This setup would give the F associated with 25% Bzero

**Comment by Rick-Methot-NOAA** [comment]
plots like the attached would be good to include in r4ss
[F_at_Blimit.xlsx](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/7041905/F_at_Blimit.xlsx)
