### ISSUE TITLE
Failure to intialize recdevs from .par file

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [nmfs-stock-synthesis/stock-synthesis#189]
I have a strange issue I cannot figure out. I am converting a 3.24U model to 3.30.17. To verify my settings are correct I want to put the MLEs from the old model into the new one. So I carefully constructed the .par file for the new one with the old values and ran it for a single iteration with command `ss -nohess -phase 500 -maxI 0`.

The recdevs in the input .par file look like this

 recdev_early:
 -0.133107041778 -0.158473917431 -0.188051619025 -
recdev1:
 -0.0471107466819 -0.251260048119 -0.235254771885 

but after running the output ss.par file has them as all zeroes:

recdev_early:
 0.00000000000 0.00000000000
recdev1:
 0.00000000000 0.00000000000

Furthermore that's what's in the control.ss_new file as well. And it's really clear from the output that it's initializing the recdevs from 0, not the values in the input ss.par file.

I was able to work around this by inputting them in the control file (and the above approach worked fine and the models matched very well).

However, I'm left a bit confused why SS was not initializing these properly. I tried this with the example model for 3.30.17 and was not able to replicate it, suggesting that I have some setting that causes this. I have no idea what. What would cause this? 

I can provide the input files offline if you want to try recreating it.

**Comment by Rick-Methot-NOAA** [comment]
Not sure what may be awry.  Please email me directly the 3.30 formatted input files, including the par file.  Converting a 3.24 par file to a 3.30 par file seems quite challenging as there is re-ordering within mgparms.

**Comment by Cole-Monnahan-NOAA** [comment]
OK Rick, incoming. Yeah it was a tedious matching exercise but I'm confident it works because the model makes the same predictions between the two (likelihoods are a bit off and I'm tracking that down still but that's irrelevant to this point).

**Comment by Rick-Methot-NOAA** [comment]
With a separate set of input files (simple), I ran to create a ss.par,  changed starter.ss to read ss.par, then ran using your script: -nohess -phase 500 -maxI 0  , and it worked as expected.

So I will test next using your files

**Comment by Cole-Monnahan-NOAA** [comment]
For posterity, I did one last test before sending. It works fine if the recdevs are inputted in the ctl file, but fails if not. So it appears it may read from the .ctl even if reading from the .par file for this model.

Let me know what you find Rick, and thanks for taking the time to help debug.

**Comment by Rick-Methot-NOAA** [comment]
Correct.  The control.ss_new file only reports the recdevs in a line preceded by a #.
Input of specific recdevs from control can only happen using this option: 
0 #_read_recdevs
which then invokes a specific format for reading individual years.  It was designed to allow SS to start from, for example a big 1977 yearclass, and not to read in all the devs.

The problem is in the manually converted starter.ss
it ends with a 999 which SS3.30 reads and concludes that is using ss_trans, so it turns readparfile from 1 to 0 to disable reading what it thinks would be a improperly formatted ss.par file.  So, I am confident your approach will work if you use a 3.30 formatted starter.ss

no charge,
Rick

**Comment by Cole-Monnahan-NOAA** [comment]
@Rick-Methot-NOAA thanks for that clever sleuthing. That makes a ton of sense. I saw that warning but had no idea it could impact the model like that. Might be worth adding a brief statement for that warning (e.g., "Note this means reading from the .par file is disabled").

I couldn't get ss_trans to run, it would error out before creating the ss_new files so that's why I was working through this manually. I now realize I have no idea how trans works, and that the ss.exe file has checks for trans behavior.

Thanks again!
