### ISSUE TITLE
rebuild.sso  Add new lines for sigma, pstar, and implementation error

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#19]
Imported from redmine, Issue [#37863](https://vlab.ncep.noaa.gov/redmine/issues/37863)
 Opened by @chantelwetzel-noaa on 2017-09-11
Status when imported: On Hold
 
The updated rebuilder requires input lines for sigma and pstar following the harvest control rule line.  Additionally, new inputs for implementation error have been added to the rebuilder executable.  SS needs to write out this section in the file as:
```
# Projection type
1
#Definiton of the control rule
0.1 0.4
# Sigma Assessment Error
0.36
# Pstar
0.45
# Constrain catches by the ABC (1=yes; 2=no)
1
# Implementation Error (0=no; 1=lognormal; 2=uniform)
0
# Parameters of Implementation Error
1 0.3
# Calculate coefficients of variation (1=yes)
0
# Number of replicates to use
10
# Random number seed
-99004
```
I have also attached an example file.

**Comment by Rick-Methot-NOAA** [comment]
@chantelwetzel-noaa    @k-doering-NOAA   
Is there anything here that is not in #232 ?

**Comment by k-doering-NOAA** [comment]
Doesn't look like it, good catch! I'll close it, but @chantelwetzel-noaa , feel free to reopen if I missed something.
