### ISSUE TITLE
Fixing recdevs not working?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#194]
See https://vlab.noaa.gov/web/stock-synthesis/public-forums/-/message_boards/view_message/17086821

according to the manual, it should be possible to fix recruitment deviations, but it is not working.

Does this seem like a bug? Or maybe I have misinterpreted what this feature does?

I can try  to reproduce with another model if this sounds like a potential bug @Rick-Methot-NOAA

**Comment by Rick-Methot-NOAA** [comment]
rec devs are a dev_vector so individual years cannot be fixed.
starting values for individual years can be read using a special format in the control file, but the entire vector is either fixed or estimated.

**Comment by k-doering-NOAA** [comment]
Ok, that makes sense, perhaps we just need a little rewording in the manual then. I was confused by the "Number of Explicit Recruitment Deviations to Read:", which you can then input individual years' recdevs, so it sounds like you can fix them even when running with estimation.

**Comment by k-doering-NOAA** [comment]
Also, thanks for addressing this!
