### ISSUE TITLE
time-vary biology for styr-1 (init_equil)

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#206]
Currently the code logic in popdyn is:
1.  call make_timevaryparm()  which files a vector from styr-1 to YrMax with values for each parameter that has some flavor of time-varying value.
2. set y=styr
3. call MGsetup(y)  which creates year specific biology using current year's value for time-varying parameters
4.  do Initial_Equilibrium conditions using styr biology.

That has been the logic for a very long time, and it means that if a user attempts time-varying difference for initial equilibrium, SS will not implement it and instead will use styr biology.

Although it might be feasible to modify code to allow for biology to change between init_equil and styr, it seems much easy for the user to just add one more year to the beginning of the time series so the change in biology can be implemented between that earlier styr and the subsequent year.

**Comment by k-doering-NOAA** [comment]
Is there a way to add a warning for this @Rick-Methot-NOAA ? We could also add this info to the manual

**Comment by Rick-Methot-NOAA** [comment]
warning would need some convoluted logic.

For recruitment regime shift parameter, the time-varying capability does
extend to year styr-1.

For all biology parameters, time-vary extends only to styr and the styr
biology is used for virgin and init_equilibrium

If user desires different biology for styr and styr-1, the user need only:
a.  add one more year to beginning of time series, this becomes the new
styr.
b.  now styr+1 (the old styr) can have time-vary biology that differs from
that for the new styr.

**Comment by k-doering-NOAA** [comment]
Ok - too bad it is not simple to add a warning! That seems like it would be the best way to alert users to the simpler, alternative setup.

Hmm, I'm trying to think of other ways to communicate this to users, but maybe the best we can do is make sure this is documented in the manual and answer people's questions if it comes up. It is good this issue was opened, too, in case someone searches the issues looking for answers.

**Comment by Rick-Methot-NOAA** [comment]
warning logic would have to be:
a.  after all time-varying linkages have been created (they are created
one-by-one as base parameters are created)
b.  does that time-vary parameter reference styr-1
c.  is the base-parameter a biology or selectivity parameter?
