### ISSUE TITLE
Remove duplicated items from vlab

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#208]
Some items are now on both vlab and github. In addition, many items are manually uploaded to vlab, which takes a lot of time.

For items that are maintained on github, provide links to the github version so that users can download the materials there instead.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , could you take a look at the [Stock Synthesis website home page](https://vlab.noaa.gov/web/stock-synthesis/home) and see if it looks good to you?

For now, I have left the exes on github, but I think we discussed just using [github releases](https://github.com/nmfs-stock-synthesis/stock-synthesis/releases)?

**Comment by Rick-Methot-NOAA** [comment]
Looks like changes have already been made to the public VLAB page?

I see several places where the viewer gets referred to the github
page, which may create confusion.  I envisioned a cleaner separation that
simply put all aspects of code management at github and kept user examples
at VLAB.

Will try to comment more later.

**Comment by k-doering-NOAA** [comment]
Sorry about that, I should have saved it as a draft instead!

My thinking was that we are actually maintaining user examples using the github repository, so it could actually be less confusing than having them duplicated on github, but I understand how having links away from vlab could be confusing also.

I'll wait for your additional comments until changing anything else.

**Comment by k-doering-NOAA** [comment]
Rick and I had a look at  the website and figured out what should stay on vlab and what to link to on github. The basic strategy was not to provide 2 links to the same place. I think we are all set now, and most things will now be linked to directly to where they are maintained, so no need to duplicate uploading to vlab!
