### ISSUE TITLE
No numbers- and biomass-at-age and at-length reported for > 1 growth patterns

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nmfs-stock-synthesis/stock-synthesis#211]
Based on reported [issue via vlab](https://vlab.noaa.gov/web/stock-synthesis/public-forums/-/message_boards/view_message/17688601) I looked back at an example model that had greater than one growth pattern per sex using SS version 3.30.08 and was able to confirm the issue.  The the numbers-at-age, numbers-at-length, biomass-at-age, and biomass-at-length are only being reported for the first growth pattern by sex with the second growth pattern for each sex printing out 0 values.  We should examine why this is occurring for models with multiple growth patterns.

**Comment by Rick-Methot-NOAA** [comment]
DId you test with current:  3.30.18 ?

**Comment by chantelwetzel-noaa** [comment]
Good point. I did not since I did not have 2 growth pattern model on hand to test associated with a newer version of SS.  We should ask Thom what version he is using as well where he is seeing this issue?

**Comment by Rick-Methot-NOAA** [comment]
My test did not show missing output.
His input should have had recdist_method 3, not 4, because he is using Morphs
When I change my example to use 4, it crashes.  Perhaps his earlier version of SS plays through but then misses some output.

**Comment by Rick-Methot-NOAA** [comment]
I added to 3.30.18 a warning that should trap for the incorrect input that caused this problem.  Closing this issue.
Rick
