### ISSUE TITLE
add warning/exit for undefine/obsolete selectivity patterns

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#228]
Apparently, if pattern 30 is chosen for length selectivity, the model will run sometimes: [example](https://github.com/futureseas/SardineMSE/blob/1e17aa45ef118f53fe91f3914699bd256da47702/EM/EM_alldat/om.ctl#L220),even though according to the manual pattern 30 should no longer be used 

An explicit exit should be added to Stock Synthesis (and r4ss read function to prevent this)

@Rick-Methot-NOAA , I can work on this  if you think it is a good idea.

**Comment by Rick-Methot-NOAA** [comment]
concur.  Please add a warning with recommendation on which better pattern to use.  Make it a warning with exit.
