### ISSUE TITLE
be more specific about when workflows run

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#234]
I recently learned you can be more specific about when github actions run, for example, only run it when .tpl files changes (and ignore changes to things like gh actions or documentation)

@Rick-Methot-NOAA , would you like me to add this to some of the jobs? I remember you brought this up a while back, but I don't think the option existed at the time. Now that it does, it seems like it would be an easy way to limit running gh actions when we don't need them.

**Comment by Rick-Methot-NOAA** [comment]
Yes.  That would be helpful.

Rick

**Comment by k-doering-NOAA** [comment]
More specific build trigger were added last month
