### ISSUE TITLE
add area-specificity to predator M2

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#235]
follow-up from issue #45 

a predator is a fleet, so operates in a specific area
natural mortality is a biological trait, so currently is not area-specific.
need to make natural mortality area-specific so that each predator can affect M2 in its area.
This means that pred_M2 should not be added to M1 in the biology step.
Instead, pred_M2(f) should be included when Z(p) is calculated within each area.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , it looks like this is the last outstanding issue according to the projects spreadsheet; will this be worked before 3.30.19? Or do we want to delay it?

**Comment by Rick-Methot-NOAA** [comment]
attached doc describes the revised logic that allows natM to be area and time specific, which is needed for predators and is needed for future development of transitional SPR (#88 ) calculations.
[natM tech doc.txt](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8635981/natM.tech.doc.txt)
