### ISSUE TITLE
FORE period in Report.sso for some tables are filled with zeros for Pacific Hake

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#242]
Starting with `NUMBERS_AT_AGE` in `Report.sso` to `BIOMASS_AT_LENGTH` the rows that pertain to the `FORE` period are populated with zero values. See example report file from the stock assessment of Pacific Hake below. I checked the `Report.sso` files from the stock assessment we did last year and they were also populated with zeros. So, it is not due to recent changes in the code. The next table, i.e., `F_AT_AGE` has actual values in the forecast period. I checked the results of a run using the "simple" model available in {r4ss} and this problem doesn't exist. So, I thought maybe it was a function of settings in `forecast.ss` and the only major difference I could find is Pacific Hake uses `2 #Bmark_relF_Basis`, whereas simple uses `1 #Bmark_relF_Basis`. I am happy to poke and prod the model or code to attempt to determine what is going on here but some guidance on where to start would be greatly appreciated. Thanks.

![image](https://user-images.githubusercontent.com/4108564/146992564-4699f96c-d208-42bb-8fc9-11feff68476a.png)

**Comment by Rick-Methot-NOAA** [comment]
I see that the forecast output exists in report.sso, but not report_mceXX.sso.  So, this should be an easy fix.

**Comment by Rick-Methot-NOAA** [comment]
fixed by turning on save_for_report before calling bigreport in mceval section.  Fix implemented on branch #218

**Comment by k-doering-NOAA** [comment]
Added @kellijohnson-NOAA as assignee just as a reminder to test if this is working
