### ISSUE TITLE
allow constant (not estimated) F with F_Method=4

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#243]
F_Method 4 was not allowing for F to be set to a constant, non-estimated value.

Solution is to allow for entry of starting phase as negative number to cause the input value for that fleet's F to stay constant and not get estimated.

link to issue #33

**Comment by k-doering-NOAA** [comment]
Remove doc tag because issue opened in doc repo: https://github.com/nmfs-stock-synthesis/doc/issues/104

**Comment by k-doering-NOAA** [comment]
removing change log label because captured in change log
