### ISSUE TITLE
mceval not working past 999

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#245]
@Rick-Methot-NOAA I am working with the newest executable of the `output_to_separate_files` branch and I cannot get samples in the mceval phase past 999. Here is a screen shot; but, I am guessing there is some index counter that is not allowing the mceval to finish. The `mcmc_counter` object is working because it will print that to the screen but the Report_mce_1000.ss was not written. I tried using a few cout statements but I was unsuccessful in finding where this is occurring. Previous tests were with less than 1000 samples so the issue was not appearing.
![image](https://user-images.githubusercontent.com/4108564/147147714-a736e367-1e8f-4e52-b93b-486c0a5f8d72.png)

**Comment by Rick-Methot-NOAA** [comment]
working on it.  strings can be tricky

**Comment by Rick-Methot-NOAA** [comment]
'''()'''''
That's me pulling last of my hair out.  Still a mystery as to why I can get it to create the output filename once with 4 character, but it dies second time through..

**Comment by Rick-Methot-NOAA** [comment]
got it.  strings are tricky.
will work on dynamic Bzero Thursday

**Comment by kellijohnson-NOAA** [comment]
This was fixed by @Rick-Methot-NOAA in a32b29d / pull request #218. Tested on the hake model with 1002 samples and it was successful.
