### ISSUE TITLE
cumulative proportion female numbers don't make sense for male to female hermaphroditic species

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#246]
Thanks to Max Cardinale for discovering this issue.

I tested an example model (below) , and found that the male and female (which I believe correspond to morphs 1 and 2, and sexes 1 and 2)  have the same cumulative proportions - is this expected? The other strange thing is that the proportion female in Max's model and in this model decreases over time, which doesn't seem right for a male to female transitioning species.

Something may be wrong in the Reporting in these numbers, or deeper in SS3, I'm not sure. I'm also not sure if this is a problem specific to male to female transitioning species, or is also seen in female to male transitioning species.

[test_mod.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/7789759/test_mod.zip)

**Comment by Rick-Methot-NOAA** [comment]
Females are always sex 1 and males are sex 2, even with males transitioning to females. So I hope what you are seeing is just a misinterpretation and not an error.

**Comment by k-doering-NOAA** [comment]
I think the proportions female at least don't make sense ( I realized I made a mistake in the specification by using 
`1 #_hermaphroditism option:  0=none; 1=female-to-male age-specific fxn; -1=male-to-female age-specific fxn`
instead of 
`-1 #_hermaphroditism option:  0=none; 1=female-to-male age-specific fxn; -1=male-to-female age-specific fxn`
but for some reason the results looked the same: 

```
     Sex Real_Age Herma_Trans Herma_Cum
3289   1        0 0.00000e+00  0.500000
3290   1        1 1.31832e-07  0.500000
3291   1        2 2.27191e-06  0.500000
3292   1        3 1.58629e-05  0.499999
3293   1        4 4.99984e-05  0.499991
3294   1        5 8.41340e-05  0.499966
3295   1        6 9.77249e-05  0.499924
3296   1        7 9.98650e-05  0.499875
3297   1        8 9.99968e-05  0.499825
3298   1        9 1.00000e-04  0.499775
3299   1       10 1.00000e-04  0.499725
3300   1       11 1.00000e-04  0.499675
3301   1       12 1.00000e-04  0.499625
3302   1       13 1.00000e-04  0.499575
3303   1       14 1.00000e-04  0.499525
3304   1       15 1.00000e-04  0.499475
3305   1       16 1.00000e-04  0.499425
3306   1       17 1.00000e-04  0.499375
3307   1       18 1.00000e-04  0.499325
3308   1       19 1.00000e-04  0.499275
3309   1       20 1.00000e-04  0.499226
3310   1       21 1.00000e-04  0.499176
3311   1       22 1.00000e-04  0.499126
3312   1       23 1.00000e-04  0.499076
3313   1       24 1.00000e-04  0.499026
3314   1       25 1.00000e-04  0.498976
3315   1       26 1.00000e-04  0.498926
3316   1       27 1.00000e-04  0.498876
3317   1       28 1.00000e-04  0.498826
3318   1       29 1.00000e-04  0.498776
3319   1       30 1.00000e-04  0.498727
3320   1       31 1.00000e-04  0.498677
3321   1       32 1.00000e-04  0.498627
3322   1       33 1.00000e-04  0.498577
3323   1       34 1.00000e-04  0.498527
3324   1       35 1.00000e-04  0.498477
3325   1       36 1.00000e-04  0.498427
3326   1       37 1.00000e-04  0.498378
3327   1       38 1.00000e-04  0.498328
3328   1       39 1.00000e-04  0.498278
3329   1       40 1.00000e-04  0.498228
3330   2        0 0.00000e+00  0.500000
3331   2        1 1.31832e-07  0.500000
3332   2        2 2.27191e-06  0.500000
3333   2        3 1.58629e-05  0.499999
3334   2        4 4.99984e-05  0.499991
3335   2        5 8.41340e-05  0.499966
3336   2        6 9.77249e-05  0.499924
3337   2        7 9.98650e-05  0.499875
3338   2        8 9.99968e-05  0.499825
3339   2        9 1.00000e-04  0.499775
3340   2       10 1.00000e-04  0.499725
3341   2       11 1.00000e-04  0.499675
3342   2       12 1.00000e-04  0.499625
3343   2       13 1.00000e-04  0.499575
3344   2       14 1.00000e-04  0.499525
3345   2       15 1.00000e-04  0.499475
3346   2       16 1.00000e-04  0.499425
3347   2       17 1.00000e-04  0.499375
3348   2       18 1.00000e-04  0.499325
3349   2       19 1.00000e-04  0.499275
3350   2       20 1.00000e-04  0.499226
3351   2       21 1.00000e-04  0.499176
3352   2       22 1.00000e-04  0.499126
3353   2       23 1.00000e-04  0.499076
3354   2       24 1.00000e-04  0.499026
3355   2       25 1.00000e-04  0.498976
3356   2       26 1.00000e-04  0.498926
3357   2       27 1.00000e-04  0.498876
3358   2       28 1.00000e-04  0.498826
3359   2       29 1.00000e-04  0.498776
3360   2       30 1.00000e-04  0.498727
3361   2       31 1.00000e-04  0.498677
3362   2       32 1.00000e-04  0.498627
3363   2       33 1.00000e-04  0.498577
3364   2       34 1.00000e-04  0.498527
3365   2       35 1.00000e-04  0.498477
3366   2       36 1.00000e-04  0.498427
3367   2       37 1.00000e-04  0.498378
3368   2       38 1.00000e-04  0.498328
3369   2       39 1.00000e-04  0.498278
3370   2       40 1.00000e-04  0.498228
```

Also see the Max's email suggesting his model has more issues than biology (not sure if this is as a result of the sex transitioning option or not)

**Comment by Rick-Methot-NOAA** [comment]
It seems that the parameter set is starting off with a 50:50 sex ratio rather than 0:100 for all male at birth.  Then the probability of changing sex is very low.  Can you try it with a small fraction female at bith and higher probability of transitioning.

**Comment by Rick-Methot-NOAA** [comment]
With the correct starting frac_female, the calculations are looking OK.
However, the reporting of hermaphroditism results in biology_at_age is much too simplistic and is incorrect for male to female approach.  
Unfortunately the values needed to report the effects of hermaphroditism are not stored, so will need to be recreated in the biology report section

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , thanks for checking this out! Sorry I didn't get around to trying it out yesterday with a realistic starting sex ratio.

**Comment by k-doering-NOAA** [comment]
removing change log label because captured in change log.

**Comment by iantaylor-NOAA** [comment]
@MOshima-PIFSC reported a plotting issue in r4ss that I tracked down to the (very appropriate) column name change from "Herma_Cum" to "sex_ratio" associated with this issue which was easily fixed in commit https://github.com/r4ss/r4ss/commit/2cbdeb0f0c6626d495c0b1d969e751ef4c23e04c.

I'm sure I just wasn't paying enough attention back in January when the change took place, but this also highlights the benefit of the automated opening of r4ss (and other repo) issues when needed as triggered by pull requests to the stock-synthesis repo as implemented by @k-doering-NOAA in https://github.com/nmfs-stock-synthesis/workflows/issues/43.

Also, thanks @MOshima-PIFSC for reporting the problem.
