### ISSUE TITLE
Lbin method 3 changed to 1 in data.ss_new

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#247]
I am working on a simulation where there are no age data and only marginal age compositions. In the input data file, I set Lbin method to 3 and the data.ss_new file has Lbin = 1. I tried to look through the code to see if some other factor led to resetting this parameter but I could not find anything. I double checked echoinput and it has
```
3 Lbin method for defined size ranges 
```
yet `data.ss_new` shows the following for all three data sections
```
1 #_Lbin_method_for_Age_Data: 1=poplenbins; 2=datalenbins; 3=lengths
```
Any thoughts regarding why this is happening?

**Comment by Rick-Methot-NOAA** [comment]
Kelli, I see nothing in the code that would change the value of Lbin_method.  When I set the hake_2018 example to have value=3, data_echo shows 3.  Please double check your example.

**Comment by kellijohnson-NOAA** [comment]
Sorry for the false alarm Rick. This appears to have been a fault of the simulation I was doing and not of code in Stock Synthesis.
