### ISSUE TITLE
enable running age structured production models directly with SS3?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#258]
There was much discussion of the ASPM diagnostic during the CAPAM workshop: http://www.capamresearch.org/Diagnostics-Workshop inspired by a presentation from @cminte ([PDF](http://www.capamresearch.org/sites/default/files/ASPM_CCA_rev.pdf)).

The status-quo approach to ASPM involves modifying the SS3 input files and re-running the model as described on this slide from @cminte below and in this R script: https://github.com/PIFSCstockassessments/ss3diags/blob/master/Cookbook/Setup_ASPM_example.R#L11-L42 (there may be more automated R scripts out there that I'm not aware of).

However, @Rick-Methot-NOAA noted in discussion today that it would be possible to build this functionality directly into SS3 so that users could request the ASPM to be run automatically in addition to the full model. 

Given the reliance on estimated selectivity parameters sometimes recdevs in ASPMdev (or ASPM-R) from the full model, this estimation step would have to take place in a phase after the main estimation phases and the main output file had been written. An alternative (or in addition) to automatically running an ASPM would be to write a control_ASPM.ss output file that fixed the appropriate parameters at the MLE estimates and leave it to the user to run it through SS3.
![image](https://user-images.githubusercontent.com/4992918/152596771-294622a1-5196-4480-b071-2a25234ef8c9.png)

**Comment by k-doering-NOAA** [comment]
It would also be discussing with the ss3diags maintainers if building it within ss3 makes more sense.

**Comment by Rick-Methot-NOAA** [comment]
This is very similar to the existing SS3 option to do DB-SRA in a dedicated first phase which works like this:
A.  read an existing model configuration, which for ASPM should be a fully converged set of selectivity parameters
B.  add 1 to the phase for all estimated parameters so none, except ln(R0), are estimated in phase 1.  (note that h and M will be fixed at input value)
C.  set logL weight to 0.0 for all data and parameters in first phase, except for the single survey  index that is a depletion survey
D.  run model for phase 1 only, so the single ln(R0) parameter gets estimated to match the single datum, the depletion survey.

For ASPM
B1.  give options to whether M and h are also estimated
C1.  give options for which surveys, instead or or in addition to, depletion survey are estimated

**Comment by cminte** [comment]
Hi Rick, if you start from an existing configuration, the rec_devs and init_rev_devs are set to zero? (they will need to be for ASPM, which will not estimate rec_devs, and ASPM-R, which will estimate rec_devs, but not for ASPM-fix, which will use the rec_devs from the full model as fixed values)
F_init and R_init also need to be estimated because they interfere in the overall scale too.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Carolina.  Yes, recdevs would need to be set to zero.
Given the number of potential options, perhaps it is better to leave ASPM as a wrapper that is outside of the SS3 code itself.  But please let us know if there is anything that can be changed inside ss3 to make ASPM easier or better.
Rick

**Comment by k-doering-NOAA** [comment]
closed because seems like it would be better as a wrapper rather than in SS3

**Comment by shcaba** [comment]
FYI- The SS-DL tool does allow for easy ASPM set-up.
@cminte, if you'd like to talk more about that, just let me know. Any improvements to the tool are welcome!

**Comment by k-doering-NOAA** [comment]
Thanks @shcaba! That is good to know, and seems like the right spot for it.

**Comment by Rick-Methot-NOAA** [comment]
I think we can close this out by adding brief description in the SS3 manual about this SS-DL option.

**Comment by kellijohnson-NOAA** [comment]
Moved to https://github.com/nmfs-stock-synthesis/doc/issues/100
