### ISSUE TITLE
posteriors.sso different if MCMC output detail 1 or 2

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#259]
I cannot figure out why posteriors.sso would be different for **FORECASTS** if MCMC output detail is 1 or 2 in starter.ss. When MCMC output detail is 1, the results match those from a previous version of SS3. When I change MCMC output detail to 2 the forecasts are different for some rows but not all. I fixed catches at zero in the forecast file and the problem did not go away. I will say that having zero catches made the SSB values for the second year of the forecast match regardless of what was in starter.ss where they did not before. I am guessing this is a timing issue and I am happy to help in any way that I can but on my own I am not quick enough to diagnose what is going on in the time frame that we need. In the mean time, do you think for Pacific Hake we should run all of our forecasts with MCMC output detail to 1? I have attached two derived_posteriors.sso files where the integer is the integer used for MCMC output detail in the starter file.
Related to #218 
[derived_posteriors_1.txt](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8013067/derived_posteriors_1.txt)
[derived_posteriors_2.txt](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8013056/derived_posteriors_2.txt)

**Comment by Rick-Methot-NOAA** [comment]
working on it; mostly this afternoon

**Comment by Rick-Methot-NOAA** [comment]
think I found it.  It is in ss_proced and where get_forecast is called

**Comment by Rick-Methot-NOAA** [comment]
@kellijohnson-NOAA 
I got identical posteriors.sso files when only changing this line from 1 to 2
1 # MCMC output detail: integer part (0=default; 1=adds obj func components); and decimal part (added to SR_LN(R0) on first call to mcmc)

Please send me the files you used to create the difference

**Comment by Rick-Methot-NOAA** [comment]
results identical when using the current ss.
[posteriors_1.sso.txt](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8019415/posteriors_1.sso.txt)
[posteriors_2.sso.txt](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8019417/posteriors_2.sso.txt)

I will try to figure out what commit after yours could have caused the fix.

**Comment by Rick-Methot-NOAA** [comment]
latest tweaks to this code are in:  fe2c8ac  from Jan 7

**Comment by Rick-Methot-NOAA** [comment]
The hake assessment is using version from Feb 10  a0f982d  for which there was a tweak in write_report  to resolve report file name problem.  There are no changes to ss_proced at that time.

I checked out a0f982d and re-compiled.  Re-ran the mceval using option 1 and option 2.  Seeing no differences based on character-by-character compare of the files.

I am out of options to explore the difference you are seeing.
I am seeing value in getting the commit code into the versioninfo such that it can be part of the model output.

**Comment by kellijohnson-NOAA** [comment]
@Rick-Methot-NOAA I just noticed that you are comparing posteriors.sso, where the differences for us were only in **derived_posteriors.sso**.

**Comment by Rick-Methot-NOAA** [comment]
duh!

**Comment by kellijohnson-NOAA** [comment]
Thank you @Rick-Methot-NOAA, I will try it out first thing in the morning.
