### ISSUE TITLE
Add error for range of month inputs (must be 1.0 - 12.99)

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#262]
Thanks Ian, for pointing this out!!

Ian wrote: 

The User Manual has example month inputs including "spawning biomass is calculated at this time of year (1.5 means January 15)", "Survey timing is now cruise-specific and specified in units of months (e.g., April 15 = 4.5)", and "The above example specifies settlement to mid-May (month 5.5)". 

I never thought about it before, but Max Cardinale (@akatan999) asked about how to associate something with the end of the year.

I found this conversion: `temp1=max(0.00001,(month-1.0)/12.); //  month as fraction of year`
in `get_data_timing(): https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_global.tpl#L213
which implies that the range of month inputs should start at 1.0 as in the example text. 

So should December 31 be entered as 12.99 (which would convert using the above code to a fraction of 0.9992), or is 13.0 an acceptable input?  Also, should there be a warning for inputs greater than the upper limit (e.g. >13.0 or >=13.0)?

KD and RM thought it would be good to add a warning or error: 

Based on the code, it seems like if using 13.0, it would convert to temp1 = 1.0, which wouldn't be right? 

Agree with Rick, the warning (or even error) is a good idea!

_Originally posted by @k-doering-NOAA in https://github.com/nmfs-stock-synthesis/doc/issues/93#issuecomment-1030182264_

**Comment by k-doering-NOAA** [comment]
I could try this, if Rick approves. Or, if @kellijohnson-NOAA feels like this would be a good one to learn @Rick-Methot-NOAA 's workflow, feel free to reassign.

**Comment by Rick-Methot-NOAA** [comment]
done.  slipped this one in with the bioecon branch
