### ISSUE TITLE
Create warning for time-varying parameter bounded link

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#267]
Part of #165

Bounded init link is [not implemented](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/bd721572cb2ad8d452756145db4794400757788f/SS_timevaryparm.tpl#L347) for linking a parameter to a model-derived quantities.

Provide a more informative error msg on why this option is not available or allowed, until #165 is taken care of in the code base.

**Comment by Rick-Methot-NOAA** [comment]
#165 has been completed, so this issue is moot and will be closed.
