### ISSUE TITLE
tag-recapture: create user filter to set min number of recaptures for inclusion of a tag-group

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#280]
some tag groups may have many releases, but few recaptures.  It seems useful to allow a user to set a filter such that that number of recaptures in time >= mixperiod exist.
This could be implemented in ss_readdata330.tpl to create a "use" flag for each tag group.
The value could be read in ss_readdata330.tpl right after the input of the value for mixperiod.
The total number of recaps is currently not counted, but easily could be in ss_readdata330.tpl.
Note: remember to only count those that are >=mixperiod.
Probably should make this a conditional input:
if(mixperiod>=0){
min_tag_recap=0.0;}
else{
mixperiod=-mixperiod;
ad_comm:  min_tag_recap;}

**Comment by Rick-Methot-NOAA** [comment]
1 # do tags (0/1)
121 # N tag groups
769 # N recap events
-4 # TG_mixperiod (latency) is the first period in which logL is calculated for this tag group (0 = release period)
#  (use negative value for TG_mixperiod to invoke reading TG_min_recap after TG_maxperiods
16 # max periods (seasons) to track recoveries, after which tags are still read into this accumulator period
2 # TG_min_recap:  N recaps >= mixperiod must be >= min_recap to include tag group in logL
# Release data for each tag group.  Tags are considered to be released at the beginning of a season (period)

ALSO*****
In compreport.sso, I now output the time in periods since release, which seems more useful for plotting and comparisons than real time, which is still there in another column

**Comment by k-doering-NOAA** [comment]
The final output looks like this:

```
2 # do tags (0/1/2). 2 means include TG_min_recap input
121 # N tag groups
769 # N recap events
4 # TG_mixperiod (latency) is the first period in which logL is calculated for this tag group (0 = release period)
16 # max periods (seasons) to track recoveries, after which tags are still read into this accumulator period
2 # Cond on Do Tags 2: TG_min_recap:  N recaps >= mixperiod must be >= min_recap to include tag group in logL
# Release data for each tag group.  Tags are considered to be released at the beginning of a season (period)
```
