### ISSUE TITLE
Is it possible to use francis reweighting with generalized size comps?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#287]
I'm not sure if this is possible to do - I assumed it would be?

**Comment by iantaylor-NOAA** [comment]
Fig below is from running r4ss on 
`test-models/models/seasonal_with_size_comp` 
(appears in the `LenComp` tab but should probably be in a separate `SizeComp` tab).
This implies that the Francis weighting functions are working for generalized size comps (or were a year ago when I last ran the code to make these plots for that model).
![image](https://user-images.githubusercontent.com/4992918/162517007-b02c185a-252d-42e0-be34-7c8aa19286e5.png)

**Comment by k-doering-NOAA** [comment]
Thank you, Ian!
