### ISSUE TITLE
changes to CATCH_AT_AGE report:40 ERA = "INIT" in November 2021

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#288]
I was updating the executable in ss3sim and noticed changes to Report.sso between 3.30.16 and 3.30.19 in CATCH_AT_AGE for the INIT era. In 3.30.18 INIT was zero for all ages. I did not change any of the input files only the executable and all of a sudden there were real positive values for each age in CATCH_AT_AGE for the initial year. The change in the code that is causing this happened sometime between a7a1321 and cd278a5. Attached are the input files and the new versus old Report.sso. Line 4163 has the differences of interest. @Rick-Methot-NOAA I am happy to help debug here, but I thought that getting your initial insight would be helpful.
[Diffbetween18v19.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8467630/Diffbetween18v19.zip)

**Comment by Rick-Methot-NOAA** [comment]
Isn't the bug the lack of output and the fix is the current code that produces that line of output?

**Comment by kellijohnson-NOAA** [comment]
Where the catches are now being reported in catch-at-age for equilibrium catch? Ian and I couldn't remember talking about theis change while we were going over the differences in the report files but maybe it was part of #192?

**Comment by iantaylor-NOAA** [comment]
This doesn't seem to just be adding output where it was missing before because the obs and expected INIT equilibrium catch is 0 as shown in the `CATCH report:15` table. So I would think that `CATCH_AT_AGE report:40` should likewise be 0 for the INIT era.

**Comment by Rick-Methot-NOAA** [comment]
OK.  I'll take a look.

**Comment by Rick-Methot-NOAA** [comment]
there was a forgotten Hrate(f,t)* in the calculation of equilibrium popdy.
fixed now.

**Comment by kellijohnson-NOAA** [comment]
Thanks @Rick-Methot-NOAA for the quick fix.
