### ISSUE TITLE
Fspr nan values when running without bmark/fcast and with hessian

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#298]
I turned off benchmark and forecast for this [two morphs model](https://github.com/nmfs-stock-synthesis/test-models/tree/two_morph/models/two_morph) and when running with hessian with ss3.30.19, I get an error in the forecast:

```
Estimating row 86 out of 86 for hessian
6 706 -log(L): 2643.81  Spbio: 99155.3 11415.8
6 707 -log(L): 2643.81  Spbio: 99155.3 11415.8
6 708 -log(L): 2643.81  Spbio: 99155.3 11415.8
6 709 -log(L): 2643.81  Spbio: 99155.3 11415.8
do benchmark and forecast if requested in sdphase
 got Fspr nan nan
array bound exceeded -- index too high in prevariable::operator()
```

this doesn't occur when I run without estimating the hessian. I'm thinking this may be a bug?

I haven't tried testing with other models, but can if it would be helpful.

**Comment by Rick-Methot-NOAA** [comment]
I suspect the code lost a conditional check for benchmark while several related items were moved around.  Should be an easy fix near bottom of ss_proced.tpl

**Comment by k-doering-NOAA** [comment]
Thanks @Rick-Methot-NOAA , I think your suspicion is correct! I submitted PR #300 for your review with what I think is the fix.
