### ISSUE TITLE
Likelihoods not matching when using Length comps vs. generalized size comps

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#304]
I tried converting a model with length comps to use generalized size comps instead. In theory, these likelihoods should match, but I couldn't get them to, even though the parameter estimates and derived values are similar. Attached are the model input files and their summary files.

[gensize_length_issue.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8593108/gensize_length_issue.zip)

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , I see this is marked as resolved (which is great!) - could you add a little context here about what was done?

**Comment by Rick-Methot-NOAA** [comment]
???  Did my write-up end up in only an email and not github?  I will check.

Issue is just that the length comps were using tail compression and tail compression is not an option for generalized size comp.  Turh=ning off tail compression for length comps results in a match.
