### ISSUE TITLE
`data.ss_new` in the code base when new file structure removed this file

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#308]
`data.ss_new` is referenced 5 times in the SS3 tpl files. I propose that we change these comments and cout statements to reflect the new file naming. Happy to do this, just wanted to check that it has not already been done in a different branch. I noticed it in the console output while I was reviewing the natural mortality stuff. 

https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/4c92b31fc7bba3780246c95d6deb7b49280a9cbb/SS_global.tpl#L113
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/4c92b31fc7bba3780246c95d6deb7b49280a9cbb/SS_global.tpl#L1012
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/4c92b31fc7bba3780246c95d6deb7b49280a9cbb/SS_global.tpl#L1015

https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/4c92b31fc7bba3780246c95d6deb7b49280a9cbb/SS_readdata_330.tpl#L2494

https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/4c92b31fc7bba3780246c95d6deb7b49280a9cbb/SS_write_ssnew.tpl#L2

**Comment by k-doering-NOAA** [comment]
Thanks, Kelli! I think this is sitting in a PR: https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/299

**Comment by kellijohnson-NOAA** [comment]
Closed with [7d9f87f](https://github.com/nmfs-stock-synthesis/stock-synthesis/commit/7d9f87fa35ba2028bc1a5208131f726dcedc0b0f), which merges in PR #299.
