### ISSUE TITLE
Clean up console output

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#313]
Updating to ADMB 13 (#257) inspired cleaning up the ss3 console output (since admb 13 includes cleanup of the admb console output options). 

Basic principles are:
- Print more to echoinput and less to the console
- Reformat messages to be more clear for users
- Reduce console output with the least verbose of the ss3 options, esp. duplicative information already available when using the admb console output default option.
- Consider how medium and most verbose ss3 options interact with the admb 13 console. Are changes needed to account for the new admb console output?

Pull request being worked in #312 .

**Comment by iantaylor-NOAA** [comment]
Surely there are lots of simulation analyses going on where nobody looks at the console output and it doesn't get piped to a text file or anything else, in which case it's just slowing things down a tiny bit.
Rather than change the existing options, I would vote for adding a -1 for no console output since 0 is taken already. This seems low priority, but also not hard to do.

**Comment by Rick-Methot-NOAA** [comment]
I vote low priority.  The runtime saved is probably less than the time it will take and go through the code and insert new IF statements to avoid the cout statements.

**Comment by Rick-Methot-NOAA** [comment]
Just watched a run scroll by and now advocate a forced change to rundetail=0 when model goes to calculate the Hessian elements.

**Comment by kellijohnson-NOAA** [comment]
I honestly do not look at the console output for anything other than warnings at the very end. I am fine with any change.

**Comment by k-doering-NOAA** [comment]
> Just watched a run scroll by and now advocate a forced change to rundetail=0 when model goes to calculate the Hessian elements.

Agree, the admb 13.0 console output interferes with the SS3 output curently during the hessian! Rick, where in the SS3 code do I look for where the hessian is calculated?

**Comment by Rick-Methot-NOAA** [comment]
That's a little tricky as it is not readily obvious without checking flags.  Look in ss_proced near the bottom where it gets to converge.

**Comment by k-doering-NOAA** [comment]
Ah, ok, thank you! I'll look more into this next week.

**Comment by k-doering-NOAA** [comment]
Just adding a note about this: Console output is cleaned up and looks good for run detail 0 with ADMB 13.0, but has not been re-worked for 1 and 2. I think we could merge in the branch once we migrate over to admb 13 (when it has been released), even if the 1 and 2 outputs haven't been re-worked.
