### ISSUE TITLE
Linux build script

### ISSUE THREAD

**Issue by arni-magnusson** [nmfs-stock-synthesis/stock-synthesis#314]
Hi, I wanted to build SS3 on Linux and found the Make_SS_330_new.sh script to have the following small issues:

1. On my machines (Debian 11 and Ubuntu 22.04), the script will not start and returns an error:
```
./Make_SS_330_new.sh: 6: Syntax error: "(" unexpected
```
2. I tried running Make_SS_330_new.sh a few times before understanding that either the 'opt' or 'safe' build must be selected. It would be nice if the --help message mentioned that.

3. The --help message starts with a warning:
```
line 86: [0+1==1]: command not found
```

4. It would be nice (and harmless) if the build script creates the build directory, rather then returning an error that the build directory does not exist.
```
line 129: cd: SS330: No such file or directory
```
The automatic creation of a build directory can be considered standard behavior in build scripts.

5. The --opt flag is essentially ignored by the script. When run with --opt, it produces a safe (not optimized) build:
```
ADMB Program: ss_opt
ADMB-12.3 safe libraries was compiled using GNU C++ 10.2.1 64bit on Sep 23 2021
```

I have prepared a pull request that fixes the above issues.

**Comment by Rick-Methot-NOAA** [comment]
Hi Arni.  Thanks for helping to improve SS3.  Kathryn will be back tomorrow and look into these suggestions.
