### ISSUE TITLE
Standardize exit message

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#320]
I noticed there are many variations on `EXIT - see warning` throughout the Stock Synthesis source code (for cases where SS3 exits early on error), including:

- `fatal read error, see warning`
- `exit, see warning`
- `SS3 will exit, see warning`
- `exit see warning`

It may be nice to clean these up so they always print the same message; perhaps we could even make a small function with the message, so it is easier to standardized the error and reduce the typing by a few keystrokes.

I wonder if this is something @nschindler-noaa would be interested in working on, if @Rick-Methot-NOAA thinks it is worth the time to do this? This seems low priority, but helpful, in my opinion.

**Comment by Rick-Methot-NOAA** [comment]
Seems like a fine suggestion.

**Comment by nschindler-noaa** [comment]
[messaging.md](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/9312783/messaging.md)
Documentation for programmers

**Comment by nschindler-noaa** [comment]
Does warning.sso need to have the number of warnings in this exact syntax?
N warnings: 4
If so, I need to redo that message. and add a separate one that is 
N notes: 3
Or something like that. Would the warnings need to be last?

**Comment by k-doering-NOAA** [comment]
As the script is currently written (see https://github.com/nmfs-stock-synthesis/test-models/blob/07f20126d2bc41747d811c3b8191d449292d9d6b/.github/r_scripts/compare.R#L184), the number of warnings does need the `N warnings: 4` exact syntax. We could change the script, though, Neal, instead of having you change your workflow.

**Comment by k-doering-NOAA** [comment]
I did modify the script to accomodate the new formatting in addition to the old. Note that currently, the comparison between new and old warnings doesn't make that much sense, though, since the new number of warnings is a subset of the total messages in the warning file. However, this won't trigger the gha to fail, so I think it is ok for now.

**Comment by nschindler-noaa** [comment]
Thank you, Kathryn. Guess there's not much else to do here. 
Congratulations to all!
