### ISSUE TITLE
Age-range Lorenzen M formulation

### ISSUE THREAD

**Issue by nathanvaughan-NOAA** [nmfs-stock-synthesis/stock-synthesis#328]
The existing Lorenzen M formulation in SS3 requires the specification of M at a fixed reference age. This is difficult in situations where M is not known and is estimated from a maximum observed age based on assumed survivorship to this age. The current practice in the southeast is to calculate the Lorenzen curve from an external growth model and use this to calculate a reference age and associated M. When growth is estimated in SS3 this often results in an internal M vector that does not achieve the original survivorship assumption. To correct this we have developed an alternative Lorenzen M formulation (See associated pull request) that takes survivorship and an age range as inputs to calculate the M vector.

**Comment by k-doering-NOAA** [comment]
This was completed in #329 and merged in
