### ISSUE TITLE
Bug: Main rec devs period < endyr and mean recruitment in forecast period produces bad gradients

### ISSUE THREAD

**Issue by nathanvaughan-NOAA** [nmfs-stock-synthesis/stock-synthesis#333]
Hi @Rick-Methot-NOAA during the development of the current scamp assessment we have discovered what appears to be a bug or at least an undesirable conflict when implementing forecasts using the mean recruitment option in a stock assessment that includes late-stage rec devs. 

#THE ISSUE
The conflict occurs in the late-stage rec devs period and the following is our interpretation of the process leading to the issue and a potential solution:
1) Model optimization seems to occur with late-stage recruitments equal to the stock recruit curve. This is consistent between models with and without forecasts turned on. 
2a) If forecasts are turned off then gradients are calculated at this point and returned in SS outputs with expected convergence to very small gradients.
2b) If forecasts are turned on then forecast period recruitments are implemented which overwrites the late-stage recruitment values that model parameters were optimized for. 
3) If forecasts were turned on then gradients are now calculated using the new forecast recruitment values in the late-stage years. This is causing many wild gradients in the model as in this specific scamp case average recruitment is about half of the SR curve predicted recruitment. 

#TESTING PERFORMED
To diagnose this problem we performed the following example runs to compare results.
1) Intended model No forecast: Main rec devs end in 2017, model end year 2020, no forecast performed (set to zero).
2) Intended model Mean recruit forecast: Main rec devs end in 2017, model end year 2020, 100 year forecast with recent mean recruitment. 
3) Intended model SR curve forecast: Main rec devs end in 2017, model end year 2020, 100 year forecast with SR curve recruitment.
4) No late-stage recruitment no forecast: Main rec devs end in 2020, model end year 2020, no forecast performed (set to zero).
5) No late-stage recruitment mean recruitment forecast: Main rec devs end in 2020, model end year 2020, 100 year forecast with recent mean recruitment. 

From these runs we observed that the intended model with no forecast (model 1) performs as expected with converged close to zero gradients on all parameters and recruitment in late-stage years equal to the SR curve expectations (approx 1250). The intended model with forecast turned on and forecast recruitment set to replicate the SR curve (model 2) produces similar results. The intended model with recent mean recruitment forecast (model 3) returns similar parameter values but with very large gradient values (up to e+9) which therefore produces an indeterminant hessian (late-stage recruitment values approx 780). Models 4 and 5 produce different results to the intended model but are consistent to each other because there are no late-stage recruitment values to overwrite.

Link to full example run results:
https://drive.google.com/drive/folders/1Kuggp1w23zWV6uRuWoSezJgb2gTJlym2?usp=sharing

#PROPOSED SOLUTION
The most reasonable solution to this appears to be to not overwrite late-stage recruitment values with the forecast specified recruitment values. This would leave late phase recruitment as equal to the stock-recruitment curve and avoid changing model values after estimation is completed. This would also ensure that model results do not change based on the specification of the forecast file.

An alternative would be to have the forecast file recruitment values implemented during the estimation period but I assume this is more complicated than the first proposal and would mean that forecast specifications could change model results which could cause difficulties and unintended results.

**Comment by Rick-Methot-NOAA** [comment]
What you are seeing makes sense from the flow of the code.
You seem to want:
a.  recdevs to stop before endyr
b.  late recdevs (which really are just forecast_devs) to stay at a value of 0.0 and not be estimated.
c.  forecast devs not to be used because the mean forecast recruitment option is chosen.

Your first choice solution seems feasible, but would need a new option.
Your backup solution does not seem to provide what you want.

I'll take a look at the feasibility.

**Comment by nathanvaughan-NOAA** [comment]
Thanks for looking into this @Rick-Methot-NOAA , I think that sums up what we are thinking. I tried identifying where exactly this occurs in the code but couldn't pinpoint it. Let me know if I can do anything to help.

**Comment by Rick-Methot-NOAA** [comment]
You want to look for the variable:  Fcast_Loop_Control(3)

It gets used to set the range of years over which forecast recruitments get applied in SS_benchfore.tpl
Then in ss_recruits.tpl, it gets used in a switch statement to determine the apporach to generating those recruits.

So, I think we could create a new variant of the switch option such that the mean_recruitment approach only gets applied to years endyr+1 and above.

**Comment by Rick-Methot-NOAA** [comment]
Nathan - were you thinking of working on this, or should I put it on my todo list?

**Comment by Rick-Methot-NOAA** [comment]
Is that case 4 only on your computer, or is there a pull request that I missed?

**Comment by nathanvaughan-NOAA** [comment]
Just local on my fork for now. 
https://github.com/nathanvaughan-NOAA/stock-synthesis/tree/Forecast-mean-rec-case-4
I am holding off on a pull request until we can decide if it is actually what we want.

**Comment by k-doering-NOAA** [comment]
Just a quick comment: @nathanvaughan-NOAA mentioned that his team found a different way to use recdevs that works for them, without needing to modify SS3, so this is no longer a high priority.

**Comment by nathanvaughan-NOAA** [comment]
Hey @Rick-Methot-NOAA, @k-doering-NOAA  is correct. After more discussion and testing, we are going to stick with the existing SS3 implementation for now. It looks like the main issue we were seeing in the gradients (and non-inverting hessian) is avoidable. Turns out that we had the recruitment averaging years set to include the late rec devs years. This led to convergence issues as the average was overwriting recruitments in the years used to calculate the initial average. Thanks for the help in identifying where to make the initial (no unneeded) changes in SS though that was very enlightening and may be helpful in the future!

**Comment by Rick-Methot-NOAA** [comment]
@nathanvaughan-NOAA   FYI see PR #473 with issue #471

**Comment by nathanvaughan-NOAA** [comment]
Thanks for the update @Rick-Methot-NOAA, always nice to hear when we are not the only ones to have these issues :)  @iantaylor-NOAA we may also have to add a warning in r4ss because there are probably a few ways the internal automatic change of the late phase devs could cause issues with read/write and plotting. An additional r4ss will crash warning could also be added to this SS warning file if we confirm that this is causing a bug.
