### ISSUE TITLE
apply warning about changed lambdas only for values in the final phase?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#339]
Would it be possible to restrict the warning about changed lambdas to cases where lambda remains changed in the final phase?

The warning "Reminder: Number of lamdas !=0.0 and !=1.0: ..." created here:
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/b18db0878421301294b72d49f3ca9b8bdbfa39c2/SS_global.tpl#L1105
is based on the `N_changed_lambdas` variable calculated during reading of the control file, here:
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/b18db0878421301294b72d49f3ca9b8bdbfa39c2/SS_readcontrol_330.tpl#L4249

The variable `N_changed_lambdas` is not used for any other purpose as far as I can tell (as opposed to `N_lambda_changes` which is used in various places), so I don't think calculating it in the final phase would impact anything else and would help users separate lambdas used to improve convergence (such as on the F ballpark) from those that have a direct impact on the final likelihood.

Lastly, there's a typo on the warning: "lamdas" should be "lambdas".

**Comment by Rick-Methot-NOAA** [comment]
The current code logic will make this hard to do.  Is the interest more in not double-counting multiple changes (as can happen with F Ballpark), or in only counting values that meet this condition in the last phase?  Easiest thing to do would be to eliminate depletion fleet and F_ballpark from the count.
