### ISSUE TITLE
Deprecate ALK tolerance

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#342]
Discussion on https://github.com/nmfs-fish-tools/SSMSE/issues/129 suggests that the ALK tolerance setting in the starter file should be deprecated. Perhaps we could add a warning first to suggest users set it to 0, then in a future release require users to reset it to 0?

@Rick-Methot-NOAA , feel free to comment on this issue if I didn't capture it how you were imagining

**Comment by Rick-Methot-NOAA** [comment]
let's retain the FUNCTION that does it, but remove it from conditional statements that invoke it and mark it as deprecated in the starter.ss file

**Comment by nschindler-noaa** [comment]
This section of code in SS_ALK.tpl is the only place calc_ALK_range is used:
`
              int ALK_phase = 0;
              if (Grow_logN == 0)
              {
                int ALK_finder = (ALK_idx - 1) * gmorph + g;
                if ((do_once == 1 || (current_phase() > ALK_phase)) && !last_phase())
                {
                  ALK_phase = current_phase();
                  ALK_range_use = calc_ALK_range(len_bins, use_Ave_Size_W, use_SD_Size, ALK_tolerance); //  later need to offset according to g
                  ALK_range_g_lo(ALK_finder) = column(ALK_range_use, 1);
                  ALK_range_g_hi(ALK_finder) = column(ALK_range_use, 2);
                }
                ALK(ALK_idx, g) = calc_ALK(len_bins, ALK_range_g_lo(ALK_finder), ALK_range_g_hi(ALK_finder), use_Ave_Size_W, use_SD_Size);
              }
              else
              {
                ALK(ALK_idx, g) = calc_ALK_log(log_len_bins, use_Ave_Size_W, use_SD_Size);
              }
`

It can be replaced by just using the "else" clause (the last line). ALK_tolerance is then ignored. We could add a Note when ALK_tolerance is read that says something like "ALK_tolerance is not currently being used, but must remain in the starter.ss file". Or we could use the word "deprecated".

**Comment by nschindler-noaa** [comment]
Wow, this really messed up the code, didn't it? Here it is without formatting:
              int ALK_phase = 0;
              if (Grow_logN == 0)
              {
                int ALK_finder = (ALK_idx - 1) * gmorph + g;
                if ((do_once == 1 || (current_phase() > ALK_phase)) && !last_phase())
                {
                  ALK_phase = current_phase();
                  ALK_range_use = calc_ALK_range(len_bins, use_Ave_Size_W, use_SD_Size, ALK_tolerance); //  later need to offset according to g
                  ALK_range_g_lo(ALK_finder) = column(ALK_range_use, 1);
                  ALK_range_g_hi(ALK_finder) = column(ALK_range_use, 2);
                }
                ALK(ALK_idx, g) = calc_ALK(len_bins, ALK_range_g_lo(ALK_finder), ALK_range_g_hi(ALK_finder), use_Ave_Size_W, use_SD_Size);
              }
              else
              {
                ALK(ALK_idx, g) = calc_ALK_log(log_len_bins, use_Ave_Size_W, use_SD_Size);
              }

**Comment by nschindler-noaa** [comment]
Thanks. I have been commenting out ALK_range stuff. 
One item needs resolution: calc_ALK requires an imatrix for low and high lengths (?). I can force it internally to 1 and nlength (which I did and it works), or I can change the calling parameters. It is only used in Make_Agelength_Key.

**Comment by Rick-Methot-NOAA** [comment]
OK to force internally to 1, nlength

**Comment by nschindler-noaa** [comment]
Ok. Creating pull request.
