### ISSUE TITLE
[Refactor]: Align logL approach across lencomp, agecomp, gen_sizecomp

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#359]
### Refactor request

The approach to calculating logL is inconsistent across lencomp, agecomp, and gen_sizecomp.  gen_size calculates logL across females and males at same time and includes ALL bins, even those in tails.  It does not include a tail compression feature.  So, it is dependent on the small added constant to allow logL calculation for bins with  no fish.  This difference is a major impediment to merging the logL calcs across the three comp  methods.
Inconsistencies include:
a.  whether or not a very tiny constant is added to expected values even when the user has not specified using an added constant 
b.  whether or not tail compression is used

### Expected behavior

Potential solution:
if there are zeroes in the comp data, then adding a small constant is needed, but only because of the ln() term in:
        SzFreq_like(SzFreq_LikeComponent(f, k)) -= SzFreq_sampleN(iobs) * SzFreq_obs(iobs)(z1, z2) * log(SzFreq_exp(iobs)(z1, z2));

but if a very tiny constant is added only to that term, the nan is avoided.
        SzFreq_like(SzFreq_LikeComponent(f, k)) -= SzFreq_sampleN(iobs) * SzFreq_obs(iobs)(z1, z2) * log(SzFreq_exp(iobs)(z1, z2) + 1.0e-15);

This approach is already used in agecomp logL by this line:
            exp_a(f, i) /= (1.0e-15 + sum(exp_a(f, i)));
   Note that this adjustment is in addition to the user-specified constant added to both the obs and expected.
   The agecomp approach is a bit more accurate as it is scaling to 1.0 after adding the tiny constant, whereas the proposed gen_size approach adds it at the final logL calculation so is off by a miniscule amount in terms of summing to 1.0, but avoids another divide computation.

Also note that the this approach is not used for length comp observations.  They rely on the user specified constant.

comments please:  @kellijohnson-NOAA @iantaylor-NOAA @chantelwetzel-noaa  @puntae

**Comment by iantaylor-NOAA** [comment]
This seems reasonable to me. 
We will want to take the time to look at comparisons of the impact of these changes across a range of models. That is, even if our automated tests don't find changes above our chosen thresholds, we should probably look at the differences to make sure we don't see anything unusual.

**Comment by k-doering-NOAA** [comment]
Good point @iantaylor-NOAA . I think one of the .csv files shows all model changes, which you could look at even if the gha doesn't flag the run as failing.

**Comment by Rick-Methot-NOAA** [comment]
A  composition vector has the females in the first half of the vector and the males in the second half.  Combined sex obs occupy only the first half.

Lencomp and agecomp approach addresses these two halves of the vector separately with code like
 obs_l(f, i)(tails_l(f, i, 1), tails_l(f, i, 2)) to address the first half of the vector
 obs_l(f, i)(tails_l(f, i, 3), tails_l(f, i, 4)) to address male half
gen_size approach processes the whole vector in one operation, effectively uses just tails_l(f, i, 1) and tails_l(f, i, 4).  This works because the added constant prevents log(0.0) from happening for any bins with no expected fish.

**Comment by iantaylor-NOAA** [comment]
Does this mean that the generalized size-comp likelihood would be a tiny bit different for a 1-sex model (where the male half of the vector doesn't exist) vs a 2-sex model with only combined-sex samples (where the male half is all zeros)? That's wouldn't be ideal, I think, but I suppose the difference would be pretty tiny anyway.

**Comment by Rick-Methot-NOAA** [comment]
With use of 1.0e-12, the difference would not be noticeable.

Also, I now realize that the efficient way to do this is to make the adjustment when calculating the tails, which happens just once in readdata.  A combined sex obs in a 2-sex model would have the upper tail set to upper end of the first half of the vector so the male bins are not included, which is what happens in the gen_size approach now.

**Comment by kellijohnson-NOAA** [comment]
Isn't some tail compression possible with the use of a negative bin in the generalized size comps? Second question, in theory would it be possible to move all length composition information to the generalized size composition section of the dat file (with some massaging of course) and not enter length compositions? Just things I am trying to think through while reading this thread.

**Comment by Rick-Methot-NOAA** [comment]
gen_size can replicate lencomp approach.  Kathryn recently did such a test.
gen_size cannot do tail compression at all.
a negative value in a gen_size bin would create an error.  
lencomp and agecomp have some bells&whistles beyond tail compression that are not available in gen_size.
much of the code for processing the lencomp and agecomp expected values are in doing the tail compression which happens separately for males and females.

**Comment by iantaylor-NOAA** [comment]
I like the way you're thinking @kellijohnson-NOAA. As FIMS adds additional composition inputs, I think it would be wise to try to follow the generalized philosophy. But at this stage with SS3, it seems easier to just support the existing users of the generalized size comp rather than move everything over.

**Comment by kellijohnson-NOAA** [comment]
I was not necessarily suggesting that all users move everything over, I was just wondering if it was possible.

And regarding no tail compression, I think I understand now. There is no tail compression in the vector assigned to a given bin but you can compress vectors across bins by using the negative value. 

I personally am not worried about a lack of tail compression for generalized size comps. I am more worried about users not knowing that a constant is being added to their data. I would think that adding a constant at the last step, which is the second proposed alternative I think, is the better option rather than a constant for every observation that is zero.

**Comment by Rick-Methot-NOAA** [comment]
I have a very stale branch for generalized agecomp.  It was created because someone in SE wanted to use otolith weight as a measure of age.  Also, as FT-NIRS ageing comes online, something generalized will be needed.

**Comment by Rick-Methot-NOAA** [comment]
Using a negative value for the compression factor means that there will be no compression because the tail is already >=0.0 before compression is even considered.  
The constant (1.0e-12) is added to all bins of the expected value to allow model to play through even if the user has not opted to use an "add_to_bin" constant.  

If the user selects the "add_to_bin" option, the value is added to all bins of the observation and all bins of the expected value.

**Comment by Rick-Methot-NOAA** [comment]
closing this issue as it is mostly dealt with in the changes made in PR #357
