### ISSUE TITLE
Need to update ADMB version info

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-stock-synthesis/stock-synthesis#373]
I was working on updating the SS3 examples in the user-examples repository and I noticed that the version in the ss_new files listed for ADMB is incorrect.
I then found that it is hardwired here
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/0f70fb715b5ae945946f2ece6e2b1eb62b1fce44/SS_versioninfo_330opt.tpl#L10
We can obviously do a quick fix by just changing the version in the tpl but I think it would be best to somehow get the version of ADMB automatically.
The real question is do we do a fix and then retag the repo with 3.30.0 and put up new executables?

**Comment by Rick-Methot-NOAA** [comment]
Appreciate you catching this Kelli.  Let's just do a quick fix and put out a replacement version of the exe.
