### ISSUE TITLE
Access of the release note of 3.30.20 

### ISSUE THREAD

**Issue by yukio-takeuchi** [nmfs-stock-synthesis/stock-synthesis#375]
I don't know if I am wrong but when I tried viewing the release note of 3.30.20 from [the link](https://docs.google.com/document/d/1zE6pWLNlRRqHe6-8JQDk67-s6_H4t3h1GuRcO7oL-1M/edit?usp=sharing) in [the release page](https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/tag/v3.30.20). I was redirected to the login site to google and consequently I was complaint by google saying "you need the access right" and failed to view the release note. Can you kindly tell me how I can view the release note?

**Comment by Rick-Methot-NOAA** [comment]
Sorry Yukio.  That link should have gone to a pdf, not the google doc.
@kellijohnson-NOAA 
[Release_Notes_3.30.20 - Sept 2022.pdf](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/9777824/Release_Notes_3.30.20.-.Sept.2022.pdf)

**Comment by kellijohnson-NOAA** [comment]
Again sorry @yukio-takeuchi that was my mistake. Thank you for posting an issue. And per @Rick-Methot-NOAA's guidance I have now linked to the appropriate pdf version of the [release notes](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/9777824/Release_Notes_3.30.20.-.Sept.2022.pdf).

**Comment by yukio-takeuchi** [comment]
@kellijohnson-NOAA and @Rick-Methot-NOAA 

Thank you for your quick action.
