### ISSUE TITLE
[Feature]: turn off some report sections when using empirical weight-at-age

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#383]
### Describe the solution you would like.

As discussed in #382, Empirical weight-at-age (EWAA) models currently include some unnecessary and potentially confusing output. Now that the report file can be customized to turn on or off any given table, it would be useful to turn off the unneeded tables any time the internal variable `WTage_rd == 1`.
This also relates to #348.

Some of the tables that could be turned off for EWAA models include
- [ ] BIOLOGY report:42
- [ ] BIOMASS_AT_LENGTH report:38
- [ ] FIT_LEN_COMPS report:27
- [ ] LEN_SELEX report:31
- [ ] selparm(Size)_By_Year_after_adjustments report:8

### Describe alternatives you have considered

Leaving things as they stand.

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa 
Can you work on this issue next?  I think all that is needed is a section of code that uses the wtage_rd switch that is read early in readcontrol to make changes to the values in pick_report_use[]  vector.

**Comment by nschindler-noaa** [comment]
Yes. I know the vector of which you speak.

**Comment by nschindler-noaa** [comment]
I am assuming that if WTage_fd == 2, there is no change.

**Comment by Rick-Methot-NOAA** [comment]
I think we turn off those reports if wtage_rd >=1.
When I added the concept of having a separate set of actions for wtage_rd==2, the intention was to be able to override the reading of everything related to growth and length.  But that code has not been developed.

**Comment by nschindler-noaa** [comment]
Okay. Thanks.

**Comment by nschindler-noaa** [comment]
Created a branch "383-feature-turn-off...". The code in SS_readcontrol_330 is changed at lines 67-80. Should the message below be ADJUST(as is) or FATAL?

  if (WTage_rd > 0)
  {
    pick_report_use(8) = "N";
    pick_report_use(27) = "N";
    pick_report_use(31) = "N";
    pick_report_use(38) = "N";
    pick_report_use(42) = "N";

    if (nobs_mnwt > 0)
    {
      warnstream << "incompatible option:  empirical bodywt-at-age is used, but meanbody_wt obs fit using growth curve";
      write_message (ADJUST, 0);
    }
  }

**Comment by Rick-Methot-NOAA** [comment]
this should be a FATAL condition

**Comment by nschindler-noaa** [comment]
And I changed that message, too.

**Comment by nschindler-noaa** [comment]
Message is changed to Warning and text to "expected value for mean body-wt will be from the growth curve, not from empirical wtatage.ss"
