### ISSUE TITLE
[Bug]: Issues using ss_trans.exe due to admb version

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nmfs-stock-synthesis/stock-synthesis#386]
### Describe the bug

I received an email from a user stating that they believe they have encountered an issue when trying to use an older ss_trans.exe that may be related to the latest admb version: 

"it seems that my previous problems were due to a compatibility issue between the ss_trans_new executable and different versions of ADMB. I had been running ADMB v12.3 and not getting the .ss_new files after the ss_trans_new executable finished. I tried running the transition executable with AMDB version 12.2 and everything converted and all the .ss_new files were produced. I recently had the ADMB program downloaded on my newer laptop so I didn't realize it was a new version. "

### To Reproduce

Attempt to run the most recent ss_trans.exe associated with 3.30.17 for a computer with the admb 12.3 and 13.0.  I do not have the most current version of admb currently on my machine and have not attempted to reproduce this issue. 

### Expected behavior

If the ss_trans.exe fails to produce the .ss_new files or run, then we may need to create a compiled version of the ss_trans.exe from at least 3.30.17 for users with the latest version of admb.

**Comment by Rick-Methot-NOAA** [comment]
I don't get it.  Once a SS3 or SS3_trans exe is created, it can be used on any machine and it does not look for ADMB on the user's machine.

**Comment by chantelwetzel-noaa** [comment]
I agree. I did not fully think through the issue when I originally posted this.  I am confused as to why supposedly the transition executable would not run correctly on one machine but would on another and there was not enough information provided to further understand what may be happening. I am going to close this issue for now but can re-open if more information is provided by the user that can clarify the issue.
