### ISSUE TITLE
guiding parameter min, max, and default values

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#40]
Imported from redmine, Issue [#64838](https://vlab.ncep.noaa.gov/redmine/issues/64838)
 Opened by @RickMethot on 2019-06-10
Status when imported: New
 
Information about a parameter's usage is known when the parameter label is assigned, but the input values for the parameter have not been read at that time.  This means that knowledge of good min and max values could be assigned at that time and then compared to the actual parameter line when it is read.

option 1:  create that info as parameters are created and then do comparison after all parameters are read
//  when a parameter is defined and its label (hence usage) is created,
//  the value of its min, max, init, prior have not yet been read
//  so when it gets created, need to pushback a code to indicate what special conditions affect it
//  also may want to save indicator of whether the parameter is multiplier, logit, etc.
//  so pushback a code to the ivector Parm_minmax
//  and add a string to the adstring_array Parm_info
  ivector minmax_types(1,10)  //  set of canned min-max typesexample
          ParmLabel+="L_at_Amin_"+GenderLbl(gg)+GP_Lbl(gp);
          Parm_info+="val";
          Parm_minmax.push_back (3);

above is comparable to the current parameter type concept, see below.

option 2:  integrate all such checks into code section that creates the parameter
parameter values themselves are read with
  init_matrix MGparm_1(1,N_MGparm,1,14)   // matrix with natmort and growth parms controls

but could be integrated into above using a pushback approach

then mgp_type is assigned later, but could be moved up to be done along with label
there already is:
  ivector mgp_type(1,N_MGparm)  //  contains category to parameter (1=natmort; 2=growth; 3=wtlen & fec; 4=recr_dist&femfrac; 5=movement; 6=ageerrorkey; 7=catchmult)

then there is a generic check for time-vary MG parms

**Comment by Rick-Methot-NOAA** [comment]
There is a start on this capability in readcontrol330.tpl

First, this concept is defined:
//  when a parameter is defined and its label (hence usage) is created,
//  the value of its min, max, init, prior have not yet been read
//  so when it gets created, need to pushback a code to indicate what special conditions affect it
//  also may want to save indicator of whether the parameter is multiplier, logit, etc.
//  so pushback a code to the ivector Parm_minmax
//  and add a string to the adstring_array Parm_info
  ivector minmax_types(1,10)  //  set of canned min-max types

Currently this is the stage of implementation, although some of the readcontrol also does:
          ParCount++;
          ParmLabel+="NatM_uniform_"+GenderLbl(gg)+GP_Lbl(gp);
          Parm_info+="val";
          Parm_minmax.push_back (3);

So the idea is that Parm_info could have entries like ""val", and "index"
and the codes for Parm_minmax could have codes like:
1 = bounded by 0 and large
2 = bounded by nil and large
3 = bounded by -large and -nil
4 = bounded by -1 and 0
etc,  and not wedded to the example list above

**Comment by Rick-Methot-NOAA** [comment]
Then, later in readcontrol and in prelim, the parm initial values are checked against the input bounds.
So if the bounds are wrong by the user, the check is weak.
With this change, the min and max can also be checked using the codes read at the time that parm labels are assigned.

**Comment by Rick-Methot-NOAA** [comment]
also see duplicate discussion in issue #73

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA should this issue be closed since it is a duplicate of #73

**Comment by Rick-Methot-NOAA** [comment]
OK unless there is relevant development info here
