### ISSUE TITLE
[Bug]: partition weighting not working when ParmSelect > Nfleets

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#402]
### Describe the bug

I tried to test the partition weighting in the attached model (based on the U.S. west coast 2019 petrale update) where there are 7 fleets and I tried to use D-M parameters to separately weight discard and retained for the first 4 fleets, resulting in 8 parameters.

This setup triggers this message: `Warning 2 Fatal Error! length D-M index for fleet: 4 is: 8 but must be an integer <=Nfleet`
which is triggered by these here:
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/2257bceea176ed5c648ac65907370a7c451bd5f1/SS_readdata_330.tpl#L1457-L1458
I tried just commenting out those two lines but then get an error
`matrix bound exceeded -- row index too high in imatrix::operator()(int, int) `
which I tracked down to this line:
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/2257bceea176ed5c648ac65907370a7c451bd5f1/SS_readcontrol_330.tpl#L4018
which I think is because `Comp_Err_Parmloc` is the wrong dimensions due to `Comp_Err_ParmCount` being too small which goes tracks back to the lines that I commented out.

At that point I was just confused, so am handing this off to @Rick-Methot-NOAA.

[2019_petrale_with_partition_weights.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/10552164/2019_petrale_with_partition_weights.zip)

### To Reproduce

Compile current "main" branch or download the artifact from the most recent call-build-ss3 and run with the files in the attached 2019_petrale_with_partition_weights.zip.

### Expected behavior

I expected the model to run with estimates of 8 values for ln(DM_theta) for each combination of discards and retained for the 4 fishing fleets.

### Which version of SS3 are you seeing the problem on?

current "main" branch

**Comment by Rick-Methot-NOAA** [comment]
readdata correctly computes that:
number of D-M definitions needed for length comp data: 8

Then in readcontrol, 
imatrix Comp_Err_parmloc(1,Comp_Err_ParmCount,1,2);  //  for each comp_err_index, locate starting parameter in parcount (2) and in Selparm (1).

So, I get correct model performance by simply removing the test against Nfleet.
I also removed the comparable test against 2*Nfleet for age and for sz as they could produce misleading error
