### ISSUE TITLE
add survey type for environment "survey" that inform recruitment devs or any time-varying parameter

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#41]
Imported from redmine, Issue [#65847](https://vlab.ncep.noaa.gov/redmine/issues/65847)
 Opened by @RickMethot on 2019-07-09
Status when imported: New
 
svy_units 31, 32 and 33 get expected value from various transformations of recruitment, but none relate directly to recr_devs
svy_units 35 allows entry of environmental data as a devs, but can only be related to parameter devs, not recr devs

Need to create svy_unit=36 to allow  direct linkage to recdev(y)

Also need an associated link function that can take 2 parameters, offset and slope

**Comment by Rick-Methot-NOAA** [comment]
This can be made more generic, but may need a new likelihood component.

All time-varying parameters (except recdevs) are contained in this table:
  matrix parm_timevary(1,timevary_cnt,styr-1,YrMax);  //  time series of adjusted parm values for block and trend

That matrix is created, row by row, in readcontrol when it calls FUNCTION:
- create_timevary() 
The matrix is populated at the top of Popdyn before starting the time series by calling FUNCTION:
-   make_timevaryparm();  //  this fills array parm_timevary for all years;
So, blocks, env, devs, trends all contribute to creating each row of parm_timevary().

Proposal:  add a logL that uses a specified row of parm_timevary to create an expected value for a survey index.
Challenges:
- [ ] how to identify which survey is to be associated with each parm_timevary row, if any.
- [ ] how to expand the set of available link functions (Q) for creation of the expected value

With this approach, it will be possible to input predator abundance as survey data and relate it to the M2 time-varying parameter.

**Comment by Rick-Methot-NOAA** [comment]
Currently, a parameter link to a env input is invoked by:
       k=int(abs(MGparm_1(j,8))/100);  //  find the env link code
       timevary_setup(6)=k;  //  link code for env
       if(MGparm_1(j,8)>0)  //  env variable used
       {
         timevary_setup(7)=int(abs(MGparm_1(j,8)))-k*100;
         k=timevary_setup(7);
//         for(y=styr-1;y<=YrMax;y++) enandv_data_pass(y)=env_data_RD(y,k);
         env_data_pass(1)=env_data_minyr(k);
         env_data_pass(2)=env_data_maxyr(k);
       }
where:
#_EnvLinks:  1: P(y)=P_base*exp(TVP*env(y));  2: P(y)=P_base+TVP*env(y);  3: P(y)=f(TVP,env_Zscore) w/ logit to stay in min-max;  4: P(y)=2.0/(1.0+exp(-TVP1*env(y) - TVP2))

Whereas for survey data as index of a parm dev, it is initiated in survey data:
#_Units:  0=numbers; 1=biomass; 2=F; 30=spawnbio; 31=recdev; 32=spawnbio*recdev; 33=recruitment; 34=depletion(&see Qsetup); 35=parm_dev(&see Qsetup)

and the Q setup specifies which dev vector to link to.

Proposal - 
modify  the env link setup for each parameter to specify which survey the parm_timevary is compared to.
This could be in addition to , or replace the current ability to compare parm_dev vector to survey data

Really convoluted.  Begs to be unified.

**Comment by Rick-Methot-NOAA** [comment]
This was completed in the simplest way possible by creating survey type 36 which uses recdev as the expected value.  So part of this family of survey types:
31=exp(recdev); 36=recdev; 32=spawnbio*recdev; 33=recruitment;
