### ISSUE TITLE
[Refactor]: remove unused variables related to ALK?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#415]
### Refactor request

While discussing workflows with @k-doering-NOAA yesterday, I looked at the artifact generated by the `call-build-ss3-warnings` workflow https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/workflows/call-build-ss3-warnings.yml and discovered that the number of warnings has significantly reduced, presumably thanks to changes between ADMB version.

The remaining warnings are shown in the warnings_ss_ref.txt file available here: https://github.com/nmfs-stock-synthesis/workflows/blob/main/reference_files/warnings_ss_ref.txt (which is copied from the artifact from the most recent github action run on the main branch a few days ago).

The warnings all seem to be related to `unused variable ‘ALK_finder’`, as well as `unused variable ‘ALK_finder’`, `unused parameter ‘ALK_range_lo’`, and  `unused parameter ‘ALK_range_hi’`. I presume that these are unused after deprecating the ALK tolerance code in Pull Request #342. If there is a good reason to keep there around, there's no problem ignoring the warnings, but if we can make the warnings go away, it will be that much easier to notice new warnings that appear in the future.

### Expected behavior

Have even fewer warnings.

**Comment by Rick-Methot-NOAA** [comment]
Neal,
can you just comment out the creation of these variables?  Or is it more complicated?

**Comment by nschindler-noaa** [comment]
Yes. right away.

**Comment by nschindler-noaa** [comment]
This is in main?

**Comment by nschindler-noaa** [comment]
created branch remove-unused-ALK-variables commented them out.
