### ISSUE TITLE
[Bug]: duplicate entries for unsexed comps getting written to CompReport.sso

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#435]
### Describe the bug

I just discovered that SS3 is writing the info on unsexed comps to CompReport.sso twice.

I compared across a couple SS3 versions and the issue seems to have appeared in mid-2022, perhaps as a result of this large change: https://github.com/nmfs-stock-synthesis/stock-synthesis/commit/a5ceb77b54ab805b2d0333ffe8e5b57a829748a1. The code to write CompReport.sso is complex and I have not determined where the issue might be, but I'm guessing that some loop intended to write both female and male comps is causing unsexed comps to be written twice.

### To Reproduce

The attached [simple_small_unsexed.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11314055/simple_small_unsexed.zip) model includes 4 input files plus CompReport.sso. The data file has a single vector of unsexed age comps in 2022 which is shown in CompReport.sso in repeated blocks: lines 1405 to 1419 and again in 1421 to 1435. The "Cum_obs" and "Cum_exp" columns differ because the calculation of those values occurs when the tables are written, but otherwise the entries are identical.

### Expected behavior

No duplicate entries for unsexed data.

### Which version of SS3 are you seeing the problem on?

3.30.20 and 3.30.21

### Additional Context

A while ago I noticed that the shading of the r4ss plots of comps for unsexed fish went away (examples at https://github.com/r4ss/r4ss/issues/785) but couldn't find the cause and it wasn't a big deal so closed the issue.
@chantelwetzel-noaa recently provided a example plot which helped me see that the issue wasn't lack of shading, but the code trying to draw two polygons on top of each other (where the shading was just applied to the space in between them and thus not visible).

I've modified r4ss to find and remove duplicate rows in CompReport (those that are identical in all respects other than "Cum_obs" and "Cum_exp", which I think should never occur under normal circumstances, so there's no rush to get this fix available, but it would be good to include in the next SS3 release.

**Comment by nschindler-noaa** [comment]
In the data file, the last age comp line has a 0 instead of a 3. I think this solves the problem. The results are different from what I can see.

**Comment by nschindler-noaa** [comment]
Sorry, I was late to the party as usual. Glad it's fixed
