### ISSUE TITLE
[Fix]: Partition warning for lencomp when partition == 2

### ISSUE THREAD

**Issue by e-gugliotti-NOAA** [nmfs-stock-synthesis/stock-synthesis#437]
### Issue description

Lisa, Nathan, and Ian are seeking advice on how to fix an r4ss bug [issue here](https://github.com/r4ss/r4ss/issues/770#issuecomment-1516392063).

### Summary of issue history, discussion, and major aspects of code development

Lisa was able to make the r4ss issue go away by changing the partition in response to this warning:
``` 
Warning 6 : fleet: 1  lencomp has obs with partition==2; will treat as partition=0 because retention not defined; N= 35
```
The model runs fine with the data in either partition 2 or 0, but r4ss crashes due to a mismatch between the "Length_comp_error_controls" output, where fleet 1 is associated only with partition 0, but the "FIT_LEN_COMPS" table and CompReport.sso show the observations associated with partition = 2 as input.

@iantaylor-NOAA said that it would be nice to avoid having r4ss crash in situations like this in the future, a few options to do this include:
- change r4ss so to treat part = 2 as part = 0 if there is no retention for this fleet
- change SS3 to write part = 2 in Length_comp_error_controls
- changing SS3 to write part = 0 in all output rather than preserving the input value of part = 2 in most places
- [more extreme] changing SS3 to stop instead of continuing when you enter data as part = 2 without having retention defined for that fleet

Nathan suggested:
```
Warning 6 : fleet: 1  lencomp has obs with partition==2; will treat as partition=0 because retention not defined, this change should also be made by the user in the original data file to avoid errors; N= 35
```

@Rick-Methot-NOAA noted that the warning message is created in ss_prelim, which is after both data and control have been read.  That gives us easier options for a fix.  We could just expand the warning as you suggest, or we could have SS3 revise the internal value for partition to 0 if do_retain=0 for that fleet.  That would be Rick's preferred solution.

A test case is available [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11502655/partition_test.zip)
### Items to do

- [x] @Rick-Methot-NOAA to revise the internal SS3 value for partition to 0 if do_retain=0 for the fleet with where partition==2. 
- [ ]  Need to revise writing of data_echo, data_expval and data_boot so the original read value is output for all of lencomp, agecomp and meansize comp.  @nschindler-noaa Can you look into this needed change?

### Does documentation already exist in the SS3 User Manual?

- [X] Yes, the link to the section in the SS3 User Manual is provided below.
- [ ] Yes, but further documentation needs to be added and is provided below.
- [ ] No, the documentation that should be added to the SS3 User Manual pertaining to this issue is provided below.

### Documentation to add to the SS3 User Manual OR link to existing documentation

- Documentation can be found in 7.14 section of the User Manual linked [here](https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual.html#length-composition-data-structure)

### Are r4ss changes needed?

- [x] No, this issue doesn't require changes to r4ss
- [ ] Yes, this issue requires changes to r4ss (if checking this box, please add iantaylor-NOAA as an Assignee in the panel to the right).
- [ ] I don't know and would like an r4ss consult (if checking this box, please add iantaylor-NOAA as an Assignee in the panel to the right).

### Are SSI changes needed?

- [X] No, this issue doesn't require changes to SSI
- [ ] Yes, this issue requires changes to SSI (if checking this box, please add nschindler-noaa as an Assignee in the panel to the right).
- [ ] I don't know and would like an SSI consult (if checking this box, please add nschindler-noaa as an Assignee in the panel to the right).

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA There won't need to be any further changes to r4ss when the SS3 value for partion right?

**Comment by iantaylor-NOAA** [comment]
@e-gugliotti-NOAA, no if SS3 changes internally as noted under "Items to do" then there should be no change needed for r4ss. I went ahead and checked the box for "No, this issue doesn't require changes to r4ss".

I like the new template!

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA great, I took you off as an assignee since no change is needed there.

**Comment by nschindler-noaa** [comment]
Looks pretty simple so far?

**Comment by nschindler-noaa** [comment]
So, mkt_l(f, i) is set to 0 if there is no retention and it is used for calcs. Then lendata(f) - the original vector is written to the *.ss_new data files. Is that the desire behavior?

**Comment by Rick-Methot-NOAA** [comment]
Neal.  What aspect of this are you working on? I thought that it had already been resolved. RickSent from my iPhoneOn May 9, 2023, at 2:28 AM, Neal Schindler ***@***.***> wrote:﻿
So, mkt_l(f, i) is set to 0 if there is no retention and it is used for calcs. Then lendata(f) - the original vector is written to the *.ss_new data files. Is that the desire behavior?

**Comment by nschindler-noaa** [comment]
I got assigned to this last week and took a look yesterday. It does look resolved hence my question before I made any changes. I guess I need to check the issues more carefully before blundering in.

**Comment by nschindler-noaa** [comment]
Discoveries:
lendata is never changed and is output in data_echo.ss_new
mkt_l(fleet, obs) is set to 0 when retention is not defined. It is output in additional data files and is used in Comp_Err_L and Comp_Err_L2 which is part of computing dirichlet_Parm. 
header_l_rd is set to lendata(1,3) and is output in the addtional datafiles. 
Age_Data is never changed and is output in data_echo.ss_new.
In SS-prelim, on line 1159, mkt_a is set to 0 if retention is not defined. It is not used to write .ss_new files.
Also, on line 1184, mkt_ms is set to 0 if retention is not defined. It is not used to write .ss_new files.
header_a is set to Age_Data(1,9) with possible changes to values 2 and 3. Values (1, 8) that include partition are output in additional data files.

To use the same approach means creating a new vector header_l that will hold the values of lendata(1,9) and be output in additional data files.

**Comment by nschindler-noaa** [comment]
Wait. header_a values in additional data files is replaces with header_a_rd values which are not changed.

**Comment by Rick-Methot-NOAA** [comment]
Good work Neal dusting off these skeletons in the attic.  I'll review later today.

**Comment by Rick-Methot-NOAA** [comment]
Looks like you are still reconciling the _rd issue.  Let me know when you want me to take a look.

**Comment by nschindler-noaa** [comment]
What is the test case for this? I can't find it anywhere

**Comment by Rick-Methot-NOAA** [comment]
test case attached
[partition_test.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11502655/partition_test.zip)

**Comment by nschindler-noaa** [comment]
Thanks. 😊 It is running better now. 
Next item is to compare sections of code.
