### ISSUE TITLE
[Warnings]: Additional parameter under "timevary Q parameters" for block in "Q_extraSD_Srv_SEAMAP_8"

### ISSUE THREAD

**Issue by e-gugliotti-NOAA** [nmfs-stock-synthesis/stock-synthesis#438]
### Issue description

@iantaylor-NOAA noted that the r4ss functions for reading and writing the control file are failing because they are looking for an additional parameter line under "timevary Q parameters" associated with the block specified for "Q_extraSD_Srv_SEAMAP_8". He is wondering why another line isn't needed? Is it that you can't have time-varying Q_extraSD? If that's the case, why not?

### Summary of issue history, discussion, and major aspects of code development
- This issue is related to #437 and #439 in that it was discussed in the same email chain.
- The files associated with this issue are confidential and can't be shared on Github but are in the email chain.
- @iantaylor-NOAA guesses that this isn't a feature that is widely used, so if it's not allowed, perhaps we could just add a warning when you specify a block for that parameter.

- @Rick-Methot-NOAA asked if SS3 works as long as you don't write the files using r4ss. @iantaylor-NOAA said that SS3 runs just fine, and writes control.ss_new which matches the input file showing a time-varying parameter line for the LnQ_base parameter but not for the Q_extraSD parameter.

- @nathanvaughan-NOAA noted that SS3 just ignores the 2 and runs as zero in this case.

### Items to do

- [ ] @Rick-Methot-NOAA to investigate this issue.

### Does documentation already exist in the SS3 User Manual?

- [ ] Yes, the link to the section in the SS3 User Manual is provided below.
- [X] Yes, but further documentation needs to be added and is provided below.
- [ ] No, the documentation that should be added to the SS3 User Manual pertaining to this issue is provided below.

### Documentation to add to the SS3 User Manual OR link to existing documentation

- The documentation is found in section 14.1 of the User Manual [here](https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual.html#using-time-varying-parameters) 
- **HOWEVER** further documentation on this may be needed to provide clarification.

### Are r4ss changes needed?

- [ ] No, this issue doesn't require changes to r4ss
- [ ] Yes, this issue requires changes to r4ss (if checking this box, please add iantaylor-NOAA as an Assignee in the panel to the right).
- [X] I don't know and would like an r4ss consult (if checking this box, please add iantaylor-NOAA as an Assignee in the panel to the right).

### Are SSI changes needed?

- [X] No, this issue doesn't require changes to SSI
- [ ] Yes, this issue requires changes to SSI (if checking this box, please add nschindler-noaa as an Assignee in the panel to the right).
- [ ] I don't know and would like an SSI consult (if checking this box, please add nschindler-noaa as an Assignee in the panel to the right).

**Comment by Rick-Methot-NOAA** [comment]
The Q_extraSD parameter is not implemented as having time-varying capability.  It is a constant applied to all observations in the time series.
