### ISSUE TITLE
[Bug]: Different length comp likelihood with partition=0 vs partition=0

### ISSUE THREAD

**Issue by e-gugliotti-NOAA** [nmfs-stock-synthesis/stock-synthesis#439]
### Issue description

When @iantaylor-NOAA  run the model without estimation after changing partition = 2 to partition = 0 for the fleets with no retention in "data_fix_partitions.ss" file instead of "data.ss", (**NOTE: these data files are confidential so are not shared on Github but are in the email chain**), he gets a different length comp likelihood when it seems like they should be the same.

### Summary of issue history, discussion, and major aspects of code development

- This issue is related to #437 and #438 in that it was discussed in the same email chain.

### Items to do

- [ ] @Rick-Methot-NOAA to investigate this issue.

### Does documentation already exist in the SS3 User Manual?

- [X] Yes, the link to the section in the SS3 User Manual is provided below.
- [ ] Yes, but further documentation needs to be added and is provided below.
- [ ] No, the documentation that should be added to the SS3 User Manual pertaining to this issue is provided below.

### Documentation to add to the SS3 User Manual OR link to existing documentation

- Documentation can be found in 7.14 section of the User Manual linked [here](https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual.html#length-composition-data-structure)

### Are r4ss changes needed?

- [X] No, this issue doesn't require changes to r4ss
- [ ] Yes, this issue requires changes to r4ss (if checking this box, please add iantaylor-NOAA as an Assignee in the panel to the right).
- [ ] I don't know and would like an r4ss consult (if checking this box, please add iantaylor-NOAA as an Assignee in the panel to the right).

### Are SSI changes needed?

- [X] No, this issue doesn't require changes to SSI
- [ ] Yes, this issue requires changes to SSI (if checking this box, please add nschindler-noaa as an Assignee in the panel to the right).
- [ ] I don't know and would like an SSI consult (if checking this box, please add nschindler-noaa as an Assignee in the panel to the right).

**Comment by Rick-Methot-NOAA** [comment]
I examined the provided example and determined that fleets 4 and 5 were using retention because they have retention code=-3 which mirrors retention from fleet 3.  So the example which turned partition from 2 to 0 was creating an inappropriate change for those fleets.  So, there is no SS3 issue to be resolved here.
