### ISSUE TITLE
conditional compilation

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#46]
Imported from redmine, Issue [#67698](https://vlab.ncep.noaa.gov/redmine/issues/67698)
 Opened by @RickMethot on 2019-08-23
Status when imported: New
 
IF statements in the code slow it down, so begin using conditional compilation so unnecessary statements are included in SS, but not in SS_OPT

include in versioninfo_safe
 #define DO_ONCE

but do not include that line in versioninfo_opt

then use it in the code as follows:
 #ifdef DO_ONCE
            if(do_once==1) echoinput<<" retained size "<<exp_l_temp_ret<<endl<<" retained age "<<exp_truea_ret<<endl;;
 #endif

so line of code will only be included in ss and will be omitted from ss_opt.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA , is there still more work to be done on this? We see some #ifdef DO_ONCE statements in the SS3 codebase, but were not sure if this was finished or still needed more work. Feel free to change priority/time

**Comment by Rick-Methot-NOAA** [comment]
experiment on my part.  Let's close.
