### ISSUE TITLE
[Bug]: gradient issue with forecast recruitment option 3

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#471]
### Describe the bug

The attached petrale model [2023.a034.001.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11840552/2023.a034.001.zip) has maximum gradient 0.0027, but when switching from Forecast recruitment = 0 = "spawn_recr" to Forecast recruitment = 3 = "recent mean...", the maximum gradient increases to 0.983 (but the results remain the same). For other configurations the bad gradient associated with Forecast recruitment = 3 is > 1.0. Thanks to @gertsevv for tracking down a change that shifted things from pretty-good to not-so-good gradients.

The estimation typically ends with "Function minimizer: Step size too small" which led me to this forum discussion https://groups.google.com/a/admb-project.org/g/users/c/6VkfepyuHrU?pli=1 where ADMB's derivative checker was suggested.

Running the derivative checker and checking the log(R0) parameter (parameter 12) shows big differences between Analytical    and Finite Diff answers if I check in the last phase (7). The values seem to match somewhat better in earlier phases, although that may be the result of changing numbering of the estimated parameters, not the phase.

### To Reproduce

To reproduce gradient change as a function of the forecast controls, run the model with forecast recruitment set to 0 or 3.

To reproduce the derivative checker diagnostic, change starter file to run model from ss.par, then run the following command, where I'm checking parameter 12 with a step size of 0.0001. I'm not very familiar with the derivative checker, so I may be doing something wrong.

```
> ss -dd 1 -phase 7
...
Starting optimization of 'ss_win' in phase 7 of 7 at Thu Jun 22 14:36:36 2023
phase= 7 | nvar=267 | iter=  0 | nll=6.48e+02 | mag=1.55e-03 | par[ 12]=SR_parm[1]
maxind = 279 maxg = 0.00155467

Entering derivative checker.
   Enter index (1 ... 267) of derivative to check.
     To check all derivatives, enter 0;
     To quit  enter -1: 12

   Enter step size.
      To quit derivative checker enter -1;
      to check for uninitialized variables enter 0): 0.0001

   X             Function      Analytical    Finite Diff ; Index
  -2.49131e-01   6.47723e+02   1.54321e-03  -2.55785e+05 ;    12
```

### Expected behavior

Meeting the convergence criterion, derivative checker showing matching values between analytical and finite diff.

### Which OS are you seeing the problem on?

Windows

### Which version of SS3 are you seeing the problem on?

3.30.21

### Additional Context

In general, the model is behaving well and mostly converging to reasonable estimates in response to changes in data or control file. Furthermore, running with `-hess_step` brings the maximum gradient down to 0 regardless of how bad it was at the end of the minimization process.

Lastly, the 2019 petrale update had a maximum gradient of 0.237 using SS3 version 3.30.13, suggesting that this may just be a fundamental issue related to tension in the model, not a problem with the software.

I don't see these things impeding our progress in finalizing the assessment next week, but the impact of changing forecast settings and the mismatch in the derivative checker made me think it's worth reporting.

**Comment by Rick-Methot-NOAA** [comment]
Oh fun.  Thanks for the good info to get me started.

**Comment by iantaylor-NOAA** [comment]
I should note that I haven't run the ADMB derivative checker on any other models in a long time, so maybe this is the way it always appears.

**Comment by Rick-Methot-NOAA** [comment]
when you run with forecast recr option 3, do you use year range starting 1876?  Seems unexpected to use all years

**Comment by iantaylor-NOAA** [comment]
Good catch. That was not intentional. We haven't taken the time to think through all the settings for a mean recruitment forecast and just switched the one value. Maybe that's the source of the problem.

**Comment by Rick-Methot-NOAA** [comment]
also.  I am worried about late_recdevs and how they are affected by option 3.  Good project while watching baseball

**Comment by Rick-Methot-NOAA** [comment]
Solution:
create a warning such that use of forecast recruitment option 3 or 4 will require last year of rec_devs to be end year.
It makes sense that the average of a range of years cannot be used as the value for one of those years.  That's the kind of recursive thing that messes up the gradient.

**Comment by iantaylor-NOAA** [comment]
Makes perfect sense. Thanks for the quick solution. I didn't remove the early/main/late division to facilitate sensitivity analyses, but the model will be simpler with just one vector since simple devs are already being used.

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa 
Hi Neal.  Can you create a suitable warning to trap for this situation?

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA should there be any additional info related to this added to the forecast section in the user manual that we are updating now - see [google doc here](https://docs.google.com/document/d/1CixVs-0sQbZA3Nf5FtJQjqBcHzOiY_12ZEteneXTL-U/edit)?

**Comment by Rick-Methot-NOAA** [comment]
Yes.  that would be a good mod to the manual

**Comment by nschindler-noaa** [comment]
After reading the man page, I need to make a couple changes to the year checking routine. I will create a new branch for just that.

**Comment by nschindler-noaa** [comment]
The branch is Fcast_MGparm_ave-year-check. SS_readdata_330.tpl lines 4227-4255 are changed (some inserted).

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa 
Did the new branch include the added warning for this issue noticed by Ian?

**Comment by nschindler-noaa** [comment]
Ack! no. Apparently, I don't know what I'm doing here. 
To be clear: When Fcast_Loop_Control(3) == 3 or 4, then the end year for recruitment needs to be endyr?

**Comment by iantaylor-NOAA** [comment]
@nschindler-noaa, yes, I think that's right. End year for main recruitment, `recdev_end` needs to equal endyr.  I'm assuming it's not allowed to be greater than endyr, but we could check for that too.

I'm also not sure what happens with any of the forecast recruitment options when you set `do_recdev` = 0, however.

**Comment by nschindler-noaa** [comment]
If do_recdev == 0, then (in SS_readdata_330)
    recdev_PH_rd = -3;
    recdev_early_PH_rd = -4;
    Fcast_recr_PH_rd = -4;
and (in SS_param)
    s = -1; // instead of YrMax

**Comment by Rick-Methot-NOAA** [comment]
Correct.  With options 3 and 4, force main recdevs to end in endyr, and tell user.

**Comment by nschindler-noaa** [comment]
the Warning reads
"Use of forecast recruitment option 3 or 4 requires last year of rec_devs to be end year."

**Comment by Rick-Methot-NOAA** [comment]
looks good.  Let's PR
