### ISSUE TITLE
Link to the SS manual in README.md is broken

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [nmfs-stock-synthesis/stock-synthesis#475]
As of July 7th, 2023 in the README.md file under "How can I learn how to use Stock Synthesis?" the link to 'Stock Synthesis user manual' is broken.

**Comment by iantaylor-NOAA** [comment]
Thanks @John-R-Wallace-NOAA, we'll get it fixed.

@e-gugliotti-NOAA, the page that redirects from that old link to the working one seems to have gotten removed in this commit: https://github.com/nmfs-stock-synthesis/doc/commit/84647d7d3e91cfddae74b3acbfba69636c267899. Was that intended or by accident?

**Comment by e-gugliotti-NOAA** [comment]
That was a mistake on my part thinking that it was the same as the duplicate user manual html that used to be written to docs. I've added it back in. @iantaylor-NOAA Can you check that the redirect works now?

**Comment by Rick-Methot-NOAA** [comment]
@e-gugliotti-NOAA 
status of this?

**Comment by e-gugliotti-NOAA** [comment]
This has been rectified.
