### ISSUE TITLE
add warning if last block is set to end in endyr

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#478]
### Describe the solution you would like.

If the last year of the **last** block of a block pattern is endyr, then the parameters using that block pattern will revert to the base value when the forecast begins in endyr+1.  That is usually not what the user intended.
A warning (suggestion) should be created to inform user of the situation and advise them to set the block's endyear far in future (say 2100) if they do not want the parameter to revert to base value at endyr+1. 

- [ ] Suggest creating this warning as soon as the block patterns are read near the top of the control file.
- [ ] Also review/edit language in manual to clarify this situation.

### Describe alternatives you have considered

none come to mind

### Statistical validity, if applicable

NA

**Comment by iantaylor-NOAA** [comment]
The suggested guidance makes sense but will lead to a warning about the end year of the block getting reset to YrMax (generated here https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/main/SS_readcontrol_330.tpl#L725-L730). 

Would it be overkill to add a new code like the ones used in the starter:
`-2 # max yr for sdreport outputs (-1 for endyr+1; -2 for endyr+Nforecastyrs)`?

Having said that, all this should only be an issue if the `Fcast_years` settings are averaging over years outside of the last block, so another option could be to add a message that says selectivity is being averaged across blocks in cases where that is happening.

**Comment by Rick-Methot-NOAA** [comment]
If end of block = endyr, then I do not see how that triggers a warning about being greater than YrMax.  But let's check.
Yes there could be interaction with selectivity averaging, but growth parameters are not averaged like that, so susceptible to this problem.  This example has block on growth and selectivity.
For selectivity, the interacting feature is in forecast:
0 # Forecast selectivity (0=fcast selex is mean from year range; 1=fcast selectivity from annual time-vary parms)

[dogfish.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/12074404/dogfish.zip)

**Comment by iantaylor-NOAA** [comment]
I was thinking of end of block equals 2100 leading to a warning which might cause folks to move away from that setting to make the warning go away and then forget to increase it if the forecast is extended.

I wasn't paying enough attention to see that time-varying growth was present but not being averaged--that's a case where a revised approach would definitely be helpful.

One more approach that I think I've seen @chantelwetzel-noaa use is to have the first block start with the unfished equilibrium year and the last block end before the last years of the model, so the final years are not in a block and represented by the base parameters. But that might be confusing when many folks are used to thinking of the initial conditions as related to the base parameters.

**Comment by Rick-Methot-NOAA** [comment]
I like Ian's idea to create this option in the readcontrol block creation code:
For the last block of a block pattern, check the ending year and reset it according to
-1 reset to endyr; -2 for endyr+Nforecastyrs

Then check to see if any block pattern ends in endyr (even those just reset above) and add this generic warning:
"At least one block pattern ends in endyr.  Check the output parameter value time series to see if the values in forecast years are as intended."

**Comment by nschindler-noaa** [comment]
When using the dogfish example, YrMax and endyr are the same as retroyr+1 (2019).  So, -1 and -2 work the same. After trying that, I set block 2 end to 2022 and got these warnings:
Warning 2 : Block:2 1 ends in: 2022 after retroyr+1:  2020
Warning 3 Adjustment: Block:2 1 ends in: 2022 reset to YrMax:  2019
Warning 4 : At least one block pattern ends in endyr. Check the output parameter value time series to see if the values in forecast years are as intended.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Neal.  Seems to be working as intended, but has lots of interaction with warnings for retro year which will confuse the user.  I'll get back to this after the weekend.

**Comment by nschindler-noaa** [comment]
Creating pull request.

**Comment by nschindler-noaa** [comment]
I moved the adjustment warnings to the front, before the warning and fatality checks which solved the conflict,
