### ISSUE TITLE
interaction of bycatch fleets and F0.1 reference point

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#48]
Imported from redmine, Issue [#68202](https://vlab.ncep.noaa.gov/redmine/issues/68202)
 Opened by @RickMethot on 2019-09-05
Status when imported: Assigned
 
find that the F0.1 search can fail if bycatch fleets are used and bycatch setting includes that fleet's catch in the catch to be optimized.
Find this issue while working on Max's vendance model that has seals as a predator via the bycatch fleet approach
Add a warning to this effect in readdata.tpl
Need to add similar note to the documentation
make a couple of tweaks to the F0.1 search to hopefully improve its performance

Note that it would be good if such searches could be on log(F) so the derived F could never go negative

**Comment by Rick-Methot-NOAA** [comment]
@k-doering-NOAA 
please check status of this
