### ISSUE TITLE
[Refactor]: adjust control of retroyr, recdev_end, and fcast_yrs

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/stock-synthesis#490]
### Refactor request

Some of the recent changes to control of recdev_end relative to endyr did not take all considerations into account.
Note that in readdata, use of retro_yr does not change endyr.  All that happens is that data existing after retro_yr are flagged with -f so are ignored in the logL.  So, obs in the retro_era anre just like obs in the forecast.

The issues that need attention are:

- [ ] adjustment of fcast_sel_yr1 and _yr2 only need to occur if Fcast_Specify_Selex == 1
- [ ] adjustment of recdev_end to be <= retroyr was not best move.  Better to adjust fcast_rec_yr2
- [ ] some warnings regarding forecast recdevs are unnecessary; it is OK to have devs when using the mean approach to getting the expected value for the forecast recruitments

### Expected behavior

better internal logic for when warnings occur and adjustments are made

**Comment by e-gugliotti-NOAA** [comment]
Adding this onto a forecast-related issue because it's so small.

Can the name of this be changed to look more like what you suggested this portion be renamed in the user manual? In the user manual it has been changed to "Base recruitment in forecast" so maybe this can be "#_Forecast base recruitment"

https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/1e126bd82664e465325e515d9a4f2eeb29fd29e5/SS_write_ssnew.tpl#L1561

**Comment by Rick-Methot-NOAA** [comment]
Good idea.  Is there other language to add to address Brian's suggestion regarding prioritization of alternative approaches?

**Comment by e-gugliotti-NOAA** [comment]
I'm not sure if there is here unless a warning needs to be issued, the documentation may be the best place to make that suggestion. I don't know the answer to Brian's question in his most recent email though, so if you could provide some guidance there, I can put it in the documentation.

**Comment by nschindler-noaa** [comment]
Fcast_Rec_yr1 and _yr2 are already adjusted to be between styr and endyr (readdata lines 4084 to 4100). This happens to all the forecast years.  I know I'm missing something here.

**Comment by e-gugliotti-NOAA** [comment]
Now in issue #493
