### ISSUE TITLE
[Feature]: Add mature_num and mature_bio to the time_series table

### ISSUE THREAD

**Issue by EJDick-NOAA** [nmfs-stock-synthesis/stock-synthesis#502]
### Describe the solution you would like.

Add mature_num and mature_bio to the time_series table. See also [#382](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/382#issue-1482287082).

### Describe alternatives you have considered

This is already calculated internally, but not reported for the entire time series.

### Statistical validity, if applicable

N/A

### Additional context

Simplifies comparison to models that track aggregate mature biomass; could consider reporting aggregate vulnerable numbers & biomass as well (or intersection of mature/vulnerable).

**Comment by Rick-Methot-NOAA** [comment]
Mature biomass and mature numbers now appear in the time_series table as shown below. And verify that they appear for all years in the spawn_recr table.

![image](https://github.com/nmfs-stock-synthesis/stock-synthesis/assets/6250016/ea8ae8ef-0df9-4804-b39f-545ded1c4c6f)

**Comment by Rick-Methot-NOAA** [comment]
That would only happen in a one sex model, in which the implied males have same biology as the females.  One-sex model in SS3 is really an asexual model.

In the two sex model I looked at I see summary bio reported separately for females and males as:  SmryBio_SX:1_GP:1	SmryBio_SX:2_GP:1
and those two values sum to the total summary_bio.   The reported mature biomass is identical to the spawning biomass, which is similar in magnitude to the female summary biomass.

**Comment by EJDick-NOAA** [comment]
Thank you for the quick response, Rick! That's exactly what I needed.
