### ISSUE TITLE
[Feature]: add line to rebuilder output consistent with latest rebuilder version (3.12j)

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [nmfs-stock-synthesis/stock-synthesis#512]
### Describe the solution you would like.

The latest version of rebuilder (3.12j December 2021) includes a line to adjust spawning output for single sex models where Sex = -1. SS3 does not output this line into rebuild.dat when "Do westcoast rebuilder" is selected in the forecast file. Therefore, can two lines be added into the rebuild.dat output?

Lines to add (default of 1 means no adjustments are done):
`# Sex ratio correction`
`1`

This needs to be added between the age specific selectivity and weights, and the M and current age structure outputs. 

### Describe alternatives you have considered

Require any user who wants to use rebuilder to enter these lines on their own

### Additional context

Here is the output (line 41-42) within a rebuild.dat file

![image](https://github.com/nmfs-stock-synthesis/stock-synthesis/assets/27824606/7933a119-a6a0-4eed-b84c-425bba38d363)

**Comment by Rick-Methot-NOAA** [comment]
How's this?

```
      rebuild_dat << "# Sex ratio correction" << endl;
      if (gender_rd < 0) 
      {rebuild_dat << fracfemale << endl;}  // where fracfemale is set to the sexratio parameter value
      else
      {rebuild_dat << "1" << endl;}  // value to indicate not used
```

**Comment by brianlangseth-NOAA** [comment]
Thanks Rick! That satisfies me.
