### ISSUE TITLE
[Bug]: Replace the word gender to sex in the comments in the data file

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nmfs-stock-synthesis/stock-synthesis#516]
### Describe the bug

I was looking over a data file and noticed that there are still several places in the comments on the data file that use the word gender rather than sex.  I propose we correct this for the newest version since it should be an easy fix. I will do a similar check in the documentation repository.

### To Reproduce

The incorrect terminology is being added to all data new files.

Example Lines Observed:
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/ff20ac8f260315a010ee45a9cc11db4f308ec0b6/SS_write_ssnew.tpl#L83
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/ff20ac8f260315a010ee45a9cc11db4f308ec0b6/SS_write_ssnew.tpl#L238
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/ff20ac8f260315a010ee45a9cc11db4f308ec0b6/SS_write_ssnew.tpl#L406
https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/ff20ac8f260315a010ee45a9cc11db4f308ec0b6/SS_write_ssnew.tpl#L430

### Expected behavior

See above

**Comment by e-gugliotti-NOAA** [comment]
Should all instances of gender in the code (not just the comments) be replaced with sex for consistency?

**Comment by chantelwetzel-noaa** [comment]
It would be great to change it in the code as well but that is a much larger undertaking. If the task of also doing the corrections in the code is too large of a task (combined with the needed testing) to be incorporated in the next release, I would prioritize making only the corrections in the output files at this point.

**Comment by Rick-Methot-NOAA** [comment]
Yes, all should be changed.
>1000 occurrences of gender in code.
global refactor almost feasible except for lines like:
    for (int sex = 1; sex <= gender; sex++)

So, for now let's just change the output.
