### ISSUE TITLE
[Bug]: Access to release note of 3.30.21

### ISSUE THREAD

**Issue by arni-magnusson** [nmfs-stock-synthesis/stock-synthesis#522]
### Describe the bug

Hi!
Similar to #375, the release notes link on the [3.30.21 page](https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/tag/v3.30.21) points to a restricted Google Doc site, so we can't read the release notes.

### To Reproduce

1. Go to https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/tag/v3.30.21
2. Click on release notes
3. I get an error message saying "You need access. Request access, or switch to an account with access."

### Expected behavior

I expected to be able to read the 3.30.21 release notes.

**Comment by e-gugliotti-NOAA** [comment]
I added a pdf file for the link that will automatically download instead of including the link to the google doc.
