### ISSUE TITLE
Wrong link in Release notes October 31, 2023

### ISSUE THREAD

**Issue by cgrandin** [nmfs-stock-synthesis/stock-synthesis#526]
In the release notes PDF dated October 31, 2023, in the paragraph:
>SS3 is now compiled with ADMB 13.1. We highly recommend that you study the new features of ADMB (listed **here**) so you can use its advanced command line features. In particular, the -hess_step command lets ADMB .....

The **here** link points to ADMB release 13.0 instead of 13.1, when 13.1 is mentioned in the text

**Comment by e-gugliotti-NOAA** [comment]
@cgrandin I just fixed it to correct the link. Thank you for letting us know that the link was incorrect.
