### ISSUE TITLE
issue with order of reports

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#54]
Imported from redmine, Issue [#69960](https://vlab.ncep.noaa.gov/redmine/issues/69960)
 Opened by @RickMethot on 2019-10-16
Status when imported: Assigned
 
The program flow with which SS proceeds from estimation, to benchmark/forecast, then to reporting needs documenting and has some convoluted aspects.

While investigating an errant calculation, I determined that the calculation of global MSY was overwriting some benchmark quantities, so when SS later went to write wtatage.ss_new, it used an incorrect value for forecast_F and this could impact wt-at-age if there was density-dependence or use of morphs.

Also, the writing of wtatage.ss_new happens during a specific iteration of time_series and forecast with save_for_report set equal to 2.  Calculation of other output quantities happens during a time_series & forecast iteration with save_for_report=1.  However, many of the report assignments are happening using save_for_report>0.  I cannot recall what logic led to writing of wtatage.ss_new during a separate model iteration.  Another aspect of the convoluted reporting logic is that forecast_report.sso is only written once but benchmark & forecast may be called multiple times.

SOme of the program flow described above happens in SS_proced.tpl, and some in the FINAL_SECTION found in SS_global.tpl

Proposal:
1.  remove the save_for_report=2 logic and write wtatage.ss_new during the save_for_report=1 iteration
2.  re-order the reporting such the order becomes:
a.  save_for_report=1 loop goes first and write most of report.sso
b.  write the ss_new files
b.  SPR/YPR profile
c.  dynamic Bzero
d.  global MSY

**Comment by Rick-Methot-NOAA** [comment]
This issue seems superceded by several code changes regarding output.  I am closing.
