### ISSUE TITLE
variance of dynamic Bzero

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#75]
Imported from redmine, Issue [#78188](https://vlab.ncep.noaa.gov/redmine/issues/78188)
 Opened by @RickMethot on 2020-04-24
Status when imported: In Progress
 
There is user interest in getting variance of dynamic Bzero

This seems feasible.  The implementation will require running dynamic Bzero in the STDQUANT function, and the creation of a sd_vector to hold the output.  That sd_vector needs to be output in a number of places with tricky indexing.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA can you provide details on how to use this option and what to look for? Happy to test but I can't really follow how to via this thread alone.

**Comment by iantaylor-NOAA** [comment]
@k-doering-NOAA there is some documentation of how to turn on this option in https://github.com/nmfs-stock-synthesis/ss-documentation/issues/31. But would be good to check that it works as described there.

**Comment by Rick-Methot-NOAA** [comment]
I think the test can be rather simple.  Just set up a run to produce the variance of dynamic bzero.  Then compare the time series of Bzero's variance to the time series of SSB's  variance.  Once that comparison is available for the hake model, then Ian, Kelli and Rick can quickly comment on its reasonableness.

**Comment by Rick-Methot-NOAA** [comment]
Stand down.  I just found some testing I did that involved both the recdev method and the dynamic bzero.  Let me summarize that and get back to the team.

**Comment by Rick-Methot-NOAA** [comment]
Here is the spreadsheet in which I summarized the results comparing the four rec_dev methods and including effect on dynamic Bzero.  There are some good comments in the text boxes on the sheet: recr_dev_method.  Alas, I cannot find the files used to produce this summary, but I presume it was "simple" and would be easy to re-create.

[dynamic_Bzero_variance.xlsx](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/6407352/dynamic_Bzero_variance.xlsx)

**Comment by Rick-Methot-NOAA** [comment]
I also think this material will be helpful for the recruitment webinar I want to prepare. So I think I will create a new issue in which we can track topics to include in that webinar; including the MCMC problem with the recdev approach no. 1

**Comment by k-doering-NOAA** [comment]
Thanks, @iantaylor-NOAA and @Rick-Methot-NOAA , all this info is really helpful!

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA did you still want testing on hake from @kellijohnson-NOAA and me? Or is the recdevs/Bzero testing sufficient?

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA have you started adding this to r4ss yet or should I start a new branch?

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA , no I haven't, so feel free to start a new branch!

**Comment by kellijohnson-NOAA** [comment]
Recreated Rick's excel figure of Dynamic B_0 for the simple model using all four do_recdev types. Next, I will compare variability of dynamic B_0 to SSB as @Rick-Methot-NOAA suggested above. Additionally, I think for my understanding it would be a useful exercise to decrease catches to very small values and see if the Dynamic B_0 matches SSB. I am also open to other ideas. Then, I will look at hake.

![image](https://user-images.githubusercontent.com/4108564/117376519-26847e00-ae86-11eb-912b-f390152c8eee.png)

**Comment by k-doering-NOAA** [comment]
Hi @kellijohnson-NOAA and @Rick-Methot-NOAA ,  this issue is still open and labelled as "needs testing". Is that still accurate?

**Comment by Rick-Methot-NOAA** [comment]
The limited testing I did when I created it showed no caution flags.
Always good if someone can take a second look, but I am satisfied if not.

Rick

**Comment by k-doering-NOAA** [comment]
closing this, as it was finished a while back. Will also remove the doc label, as Ian created documentation for this a while back (see comments on this issue thread.
