### ISSUE TITLE
calculate fleet-specific fishery impacts relative to dynamic B0

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#76]
Imported from redmine, Issue [#78212](https://vlab.ncep.noaa.gov/redmine/issues/78212)
 Opened by @iantaylor-NOAA on 2020-04-24
Status when imported: New
 
Low priority wishlist item copied from #78188

The IATTC and IOTC and maybe other groups have used figures like the following (pasted from https://www.iattc.org/PDFFiles/StockAssessmentReports/_English/No-20-2019_Status%20of%20the%20tuna%20and%20billfish%20stocks%20in%202018.pdf) to show the contributions of different fisheries to the difference between spawning biomass without fishing and spawning biomass with fishing. This is done by iteratively running SS using the .par file to keep all estimated parameters while progressively changing the input catch for each fleet to 0. It could save a lot of time to have this done automatically within SS. The challenge would be that from what I understand the fishery sectors shown in these figures sometimes represent multiple fisheries in the model so they would need to use something like the forecast allocation groups. Also the order in which they are removed presumably impacts the results as well, so additional inputs might be needed. Alex da Silva, Carolina Minte-Vera and Dan Fu are the folks I've corresponded with about this in the past.

An alternative to building this into SS or sticking with the status-quo of manual approaches would be to create an r4ss function to do this. Dan Fu shared some R code he wrote that could be generalized for this purpose.

!dynamic_B0_IATTC.png!

**Comment by k-doering-NOAA** [comment]
Check in with folks listed to see what the status is.

@aaronmberger-nwfsc, perhaps you know?

**Comment by iantaylor-NOAA** [comment]
There is more discussion about this at https://github.com/r4ss/r4ss/issues/23. After adding the basic plot without fleet-specific impacts, I chose to close that r4ss issue with the note: "We can open a new issue for the fleet-specific allocation of the impact of fishing discussed above if that becomes a higher priority." 

I think we could probably close this one too. The folks who are making plots like these for tuna stocks can presumably continue to do so with their R code outside of stock-synthesis so the benefit of investing the time it would take to add this option internally doesn't seem worth the payoff.

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA ! I will close for now, but others can reopen if it seems appropriate.
