### ISSUE TITLE
bug: mean size-at-age reporting when platoons>1

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#87]
Imported from redmine, Issue [#82912](https://vlab.ncep.noaa.gov/redmine/issues/82912)
 Opened by @RickMethot on 2020-09-16
Status when imported: Resolved
 
All mean size-at-age output for non-central platoons is shown as 0.0.
The ALK for each is reported and they differ, as they should.
The mean bodywt timeseries gets reported for each and this seems correct.

So, some logic problem is zeroing out the mean length-at-age for the non-central morphs.

**Comment by iantaylor-NOAA** [comment]
I tried to test this using the attached model files: [platoons.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/6475546/platoons.zip) and the ss.exe artifact from [the most recent build-win github action](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/runs/839628487) and "nan" values appear during the estimation that were not present when these same files were run with 3.30.16.02. Looking at ParmTrace.sso (included in zip) doesn't reveal anything obviously wrong.

The good news is that I'm seeing a change in the expected size at a given age (figure below). Even though the change is very small, I'm assuming this means that this output is being aggregated across platoons. I have no recollection of which model or SS version exhibited the problem or if this was the way the issue appeared so this may not be the right test to confirm that things are indeed resolved.

@Rick-Methot-NOAA can you take a look at the source of the "nan" values and confirm whether my test is adequate to confirm that this issue has been fixed?

```
# commands to make figure below
mod <- SS_output('c:/SS/git/ss-test-models/models/platoons/')
plot(mod$ladbase$Yr[mod$ladbase$Month == 3 & mod$ladbase$Bin==5],
		 mod$ladbase$Exp[mod$ladbase$Month == 3 & mod$ladbase$Bin==5],
		 xlab = "Year", ylab = "Mean size at age 5")
```
![image](https://user-images.githubusercontent.com/4992918/118200460-f00cad00-b409-11eb-8a18-ea69953a3f21.png)

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA , just wanted to check in - anything else needed on this one?

**Comment by iantaylor-NOAA** [comment]
Seems like we're all sorted. Thanks for the reminder.
