### ISSUE TITLE
check lambda impact on likelihood for catch vs. equilibrium catch

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#91]
Imported from redmine, Issue [#83773](https://vlab.ncep.noaa.gov/redmine/issues/83773)
 Opened by @iantaylor-NOAA on 2020-10-09
Status when imported: Resolved
 
@richard.methot found that the "Malawi_Demo" model used in the October 2020 course had lambda = 0 for the catch likelihood (like_comp = 8) which seemed to be interacting with the initial equilibrium catch likelihood, when that should have required a separate entry for like_comp = 9.

**Comment by Rick-Methot-NOAA** [comment]
a quick targeted test should resolve this issue easily

**Comment by k-doering-NOAA** [comment]
I just realized this was never tested; do we still need, @Rick-Methot-NOAA ?

**Comment by Rick-Methot-NOAA** [comment]
it was pretty simple and I did a near unit test when I fixed it.  So I am confident it is OK.  Rarely used
